### ISSUE TITLE
Linking Individual Pages into Homepage.

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#1]
Everyone has opened their page. The pages should be reachable via links from the homepage.

**Comment by egetaga** [comment]
Linked the personal pages of Harun SAMİ, Kadir Gökhan SEZER, Kamil KORKUT,  Mustafa ATAY, Ömer ÖZDEMİR, Ahmet YAZICI

**Comment by kadirgokhann** [comment]
Linked the pages of Harun Erkurt, Ege Onur Tağa, Ece Sarkin, Elif Nur Akalin, Efekan Kavalci into homepage.

**Comment by egetaga** [comment]
Reviewed all the hyperlinks. It seems fine. Closing the issue.
