### ISSUE TITLE
Favorite github repositories of team members

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#10]
Team members should add their favorite GitHub repositories on with their comments regarding why they like it on [this wiki](https://github.com/bounswe/bounswe2022group1/wiki/Favorite-Github-Repositories)

**Comment by omerozdemir1** [comment]
I have added [Pythonic Data Structures and Algorithms](https://github.com/keon/algorithms)

**Comment by efekankavalci** [comment]
I have added [PyTorch Sentiment Analysis](https://github.com/bentrevett/pytorch-sentiment-analysis)

**Comment by mstfatay** [comment]
I have added [first-contributions](https://github.com/firstcontributions/first-contributions)

**Comment by ecesrkn** [comment]
I have added [algorithm-visualizer](https://github.com/algorithm-visualizer/algorithm-visualizer)

**Comment by kamilkorkut** [comment]
I have added [detectron](https://github.com/facebookresearch/Detectron)

**Comment by harunerkurt** [comment]
I have added [Free Code Camp](https://github.com/freeCodeCamp/freeCodeCamp)

**Comment by elxif** [comment]
I have added [AppFlowy](https://github.com/AppFlowy-IO/AppFlowy)

**Comment by gecemavisioa** [comment]
I have added VueJS

**Comment by acyishere** [comment]
I have added [awesomePython](https://github.com/vinta/awesome-python)

**Comment by egetaga** [comment]
I had added [pytorch-imagk-models](https://github.com/rwightman/pytorch-image-models) when I opened the issue. Since everyone added their favorite GitHub repositories, I am closing the issue.
