### ISSUE TITLE
Class Diagram - Forum

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#100]
I should add the communication channel - "Forum" - as a class to the class diagram. Also, I should provide fields, method signatures and relations to the other classes.

**Comment by ecesrkn** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/43001709/161834431-dde1fbad-30a8-4cca-81a3-e7793c4daec8.png">

The task is completed as can be seen on our Lucidchart diagram [page](https://lucid.app/lucidchart/08733f3d-f1d2-4959-8c65-d71e0545c9f2/edit?invitationId=inv_fd1baad2-95e7-4994-968f-a8fb97c3a84a)
Review is needed.

**Comment by egetaga** [comment]
I have thought a lot for finding an error but couldn't find any, except **related_course** being a public field. I am fixing this and closing the issue. 

Well done and very neat work! Thanks Ece.

**Comment by ecesrkn** [comment]
Thanks for the attention @egetaga I have corrected it just now.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/43001709/161849461-962ff273-00cb-4595-a7a4-61f1a8407115.png">
