### ISSUE TITLE
Class Diagram: Annotation Text 

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#101]
![text](https://user-images.githubusercontent.com/74719781/161840582-ccd6a7e5-dedc-4688-9877-6e2c239f3e83.PNG)

Annotation Text has fields such as text, color, and font spefications. Also has getter and setter methods for these.

**Comment by omerozdemir1** [comment]
- All fields are public but you define setter and getter methods. I think you should either make the fields private and define setter and getter methods or make the fields as public but no getter and setter methods.

Other than that it seems nice, thank you.

**Comment by harunerkurt** [comment]
I checked and I don't see anything missing so I'm closing it
