### ISSUE TITLE
Annotation Image Class Diagram

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#102]
![image](https://user-images.githubusercontent.com/74719781/161840777-94bfa01c-a791-439c-adf4-ddb0036c03f0.PNG)

Annotation Image has a url text that takes an image online.

**Comment by omerozdemir1** [comment]
I reviewed your work. I think, delete method and annotation_id is needed.

**Comment by omerozdemir1** [comment]
I think you should define image_url as private field since there is a getter and setter method for that.

**Comment by harunerkurt** [comment]
I checked the diagram. very nice thanks
