### ISSUE TITLE
Class Diagrams: Content, Video, Image, Text, Link

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#103]
We noticed that each course needs a list of Contents. 
To ensure that, an abstract class "Content", and its child, "Content, Video, Image, Text, Link" should be created.

**Comment by gecemavisioa** [comment]
![my place](https://user-images.githubusercontent.com/73769340/161840998-55075091-de28-4141-a437-3531c5578bdc.png)
With the help of my team members @omerozdemir1 and @acyishere, we designed necessary classes.

**Comment by gecemavisioa** [comment]
Review needed.

**Comment by omerozdemir1** [comment]
- I think no need to store video_length in the video class.
- All fields are public but you define setter and getter methods. I think you should either make the fields private and define setter and getter methods or make the fields as public but no getter and setter methods.

 Other than that it seems nice, thank you.
