### ISSUE TITLE
Annotation Abstract Class Diagram

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#104]
![abs](https://user-images.githubusercontent.com/74719781/161841035-4ac45ddc-1902-48b2-843e-ff0e3020ec25.PNG)

The abstract class Annotations has a related content id and owner id.

**Comment by omerozdemir1** [comment]
I reviewed your work. I think, delete method and Annotation id is needed.

**Comment by acyishere** [comment]
Good point, on it

**Comment by acyishere** [comment]
Solved and closed
