### ISSUE TITLE
Use Case Diagram - Communication Channel

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#107]
We should append the Communication channel section to the [use case diagram.](https://lucid.app/lucidchart/bcda2246-9b5b-428c-a296-b54e741ff797/edit?invitationId=inv_09715d96-c97a-49a5-80b6-008b2aea1fe4)
I think we can split it into two "Forum" and "Messaging". I suggest I may take Messaging and @egetaga you can handle the other one.

**Deadline** April 6, 15:00

**Comment by ecesrkn** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/43001709/161848477-d2c270c9-d0cf-4290-a2bf-409da018141f.png">
Messaging use case is created.

**Comment by egetaga** [comment]
As @ecesrkn suggested, I am taking the responsibility of **Forum** diagram. The forum shall include:

- leaving comment for the course and lecturer
- asking and answering questions
- creating polls in anonymous, multiple answer and quiz mode. 
- posting a content on the forum page 
- sharing image-like resources

According to these specifications, I have created a diagram:
<img width="495" alt="Screen Shot 2022-04-06 at 00 20 51" src="https://user-images.githubusercontent.com/42147612/161851210-f9b3acc9-818a-4785-9854-0d2690d4e777.png">

**Comment by egetaga** [comment]
@efekankavalci Could you review and close the issue after revision (if possible)?

**Comment by efekankavalci** [comment]
I reviewed it and I think it looks okay. There is one thing I thought of, posting content and sharing image seem like similar cases, maybe sharing image can be an extension of posting content.

**Comment by ecesrkn** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/43001709/163322934-c46c5fee-9bd9-4c45-841a-b7ced216aab1.png">
I removed "Verification of user's privacy preferences" after the feedback from the Problem Session on 06.04.2022.

**Comment by efekankavalci** [comment]
As I was doing a sequence diagram I observed the need of a relation to subject in forum cases. I added it. You can see it as below and see the [related issue](https://github.com/bounswe/bounswe2022group1/issues/129#issuecomment-1098555860)
![image](https://user-images.githubusercontent.com/56485487/163458447-708b6063-6397-4fab-aff9-8a177d4c4ef3.png)
