### ISSUE TITLE
Use Case Diagram: Note Taking

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#108]
In preparation of the use case diagram, we have decided to design the note taking diagram according to the [requirements 1.2.4](https://github.com/bounswe/bounswe2022group1/wiki/Requirements). So according to the requirements:

> 1.2.4.1 Users should have a page to take notes while taking the course.
> 1.2.4.2 Users should have access to different colors and fonts while taking notes.
> 1.2.4.3 User notes should stay unchanged when user loggs off.

We should prepare a note taking diagram suiting to 1.2.4.1, 1.2.4.2, 1.2.4.3.

**Comment by mstfatay** [comment]
I should add that Note Taking is connected to user stickman figure and extends to Enroll Course. However, it shouldn't extend to Enroll Course. Instead, Course should include Note Taking. What do you think about it? @efekankavalci @egetaga

**Comment by egetaga** [comment]
Considering your review, I modified the the diagram and removed the extension. Now that everything seems fine regarding the Note Taking diagram, I am closing the issue.
