### ISSUE TITLE
Use Case Diagram: Registration

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#109]
We should create a part of use case diagram for registration according to the things we discuss in our meeting and [requirements](https://github.com/bounswe/bounswe2022group1/wiki/Requirements). This part should include logging in, logging out, password handling, and error handling.

Deadline: 06.04.2022

**Comment by mstfatay** [comment]
I created it. The screenshot of it is as follows:
It doesn't seen in image but logout and login elipses are connected to user stickman figure. This diagram handles verifying password and errors too.

![regis](https://user-images.githubusercontent.com/46002371/161851345-8c150b88-c256-4edf-b357-41ef55c8e388.png)

**Comment by ecesrkn** [comment]
I did the review. Thank you @mstfatay it looks well done and consistent with our requirements. I'm closing the issue.
