### ISSUE TITLE
Use Case Diagram - Search ( Dark Green )

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#110]
![asa](https://user-images.githubusercontent.com/74719781/161848662-b2cd7f41-c960-4511-85f2-4564e5fcca5b.PNG)

Search use case diagram needs semantic search according to requirements, semantic research is by context and by synonym. We get results including Course or User which also include Lecturer or Learner.

Further rewiev needed.

**Comment by acyishere** [comment]
Changing extend and include arrows according to annotation rules.

**Comment by omerozdemir1** [comment]
I reviewed your work. It seems nice, thanks!
