### ISSUE TITLE
Use Case Diagram: View

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#111]
We are designing the use case diagram of our project.
View functionality should be designed according to the determined requirements and the mockups of the project.

**Comment by gecemavisioa** [comment]
![myplace](https://user-images.githubusercontent.com/73769340/161849745-8fae15c6-d678-4502-b4f8-770c482721d7.png)
I designed the "View" part of the diagram

**Comment by efekankavalci** [comment]
I reviewed this part, and I think it looks good.

> ![myplace](https://user-images.githubusercontent.com/73769340/161849745-8fae15c6-d678-4502-b4f8-770c482721d7.png) I designed the "View" part of the diagram
