### ISSUE TITLE
Use Case Diagram: Register

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#112]
I went over the [requirements of our project](https://github.com/bounswe/bounswe2022group1/wiki/Requirements) and [Fundamental features](https://github.com/bounswe/bounswe2022group1/wiki/Fundamental-Features-of-the-Project) in order to design use case diagram for the register system.
The following is the final version of what I have done.
Review is needed!
![image](https://user-images.githubusercontent.com/62199007/161987495-a99d21e6-9f39-4b05-9b89-b2bcf510bce0.png)

**Comment by efekankavalci** [comment]
I believe register with credentials and register with  google needs to be extensions of register. Straight lines are not used between use cases.

**Comment by omerozdemir1** [comment]
Good point, thanks for the feedback. I made the necessary modification. It seems correct to me. Therefore, I will close the issue. However, you can reopen it if you see any mistake.
