### ISSUE TITLE
Use Case Diagram - Edit Profile, Enroll Course

### ISSUE THREAD

**Issue by efekankavalci** [bounswe/bounswe2022group1#113]
We discussed the [template I created](https://github.com/bounswe/bounswe2022group1/issues/87) on Lucidchart and shared the writing parts. I will write edit profile, enroll course parts with the details we discussed.

**Comment by efekankavalci** [comment]
I wrote the sections and need someone to review. 

<img width="238" alt="image" src="https://user-images.githubusercontent.com/56485487/161850131-2e992f03-6002-4d92-8780-b104de4ff744.png">

<img width="164" alt="image" src="https://user-images.githubusercontent.com/56485487/161850203-30a3c54f-3d28-4f9e-be98-07e587845687.png">

**Comment by acyishere** [comment]
reviewed, seems in order. Closing the issue
