### ISSUE TITLE
Use Case Diagram: Login by Lecturer

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#120]
The diagram now does not say that lecturer has a login class, but for the user it says. The way user has should be implemented also to the lecturer.

Deadline: 06.04.2022

**Comment by kadirgokhann** [comment]
The login case is added.
<a href="https://ibb.co/tqSNLmd"><img src="https://i.ibb.co/McbjB2X/Ekran-Resmi-2022-04-06-01-20-02.png" alt="Ekran-Resmi-2022-04-06-01-20-02" border="0"></a>

**Comment by kadirgokhann** [comment]
After the PS and advices from Egemen, this case should be fixed. The last version:
<img width="527" alt="Ekran Resmi 2022-04-07 04 38 19" src="https://user-images.githubusercontent.com/74508086/162103166-2c40e5dd-3d6d-4bfd-8ced-f72b5da0421c.png">

**Comment by efekankavalci** [comment]
I noticed that there are Login cases for both student and lecturer, therefore I am re-opening this issue to clarify. The Student actor is a parent of lecturer, every lecturer is a student, the students who opens a lecture a lecturers. You can see the corresponding requirement of Lecturer [here](https://github.com/bounswe/bounswe2022group1/wiki/Requirements#1-functional-requirements). Therefore I think Login case in the student part also encompasses the login of lecturer, below is an excerpt. Can you confirm? We can delete the duplicate login after you review.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/56485487/163018928-5cae07ec-6659-453d-ba5e-28c48b19a0c0.png">

**Comment by efekankavalci** [comment]
I have made the change I mentioned, and I am closing this issue.

> I noticed that there are Login cases for both student and lecturer, therefore I am re-opening this issue to clarify. The Student actor is a parent of lecturer, every lecturer is a student, the students who opens a lecture a lecturers. You can see the corresponding requirement of Lecturer [here](https://github.com/bounswe/bounswe2022group1/wiki/Requirements#1-functional-requirements). Therefore I think Login case in the student part also encompasses the login of lecturer, below is an excerpt. Can you confirm? We can delete the duplicate login after you review. <img alt="image" width="308" src="https://user-images.githubusercontent.com/56485487/163018928-5cae07ec-6659-453d-ba5e-28c48b19a0c0.png">
