### ISSUE TITLE
Sequence Diagram: Login as User

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#121]
For the sequence diagram, the first diagram that is "login as user on web" should be created. Since this is the first template, the way how we design it should be also searched on the Internet and in the old GitHub accounts. Then appropriate diagram of our project should be finalized.

Deadline: 07.04.2022

**Comment by kadirgokhann** [comment]
This [link](https://www.lucidchart.com/pages/uml-sequence-diagram#:~:text=A%20sequence%20diagram%20is%20a,to%20document%20an%20existing%20process.) helped me a lot, one can also benefit from this link.

**Comment by kadirgokhann** [comment]
<a href="https://ibb.co/w0b7Mt2"><img src="https://i.ibb.co/p0sQJqk/Ekran-Resmi-2022-04-06-02-35-18.png" alt="Ekran-Resmi-2022-04-06-02-35-18" border="0"></a>

**Comment by kadirgokhann** [comment]
After PS, we are said that this was wrong. New version is 
<img width="802" alt="Ekran Resmi 2022-04-07 04 56 23" src="https://user-images.githubusercontent.com/74508086/162104841-b377c7e1-e398-4bc4-9951-1ac006cbd03a.png">

**Comment by acyishere** [comment]
On alternative part creates a session should be after creates session ( according to timeline ). Left arrow should be at a lower stage than the right one.

**Comment by kadirgokhann** [comment]
I changed the diagram. Can you check again?
<img width="832" alt="Ekran Resmi 2022-04-15 13 55 54" src="https://user-images.githubusercontent.com/74508086/163563067-a592a9d5-3da5-4771-a12c-b0737bb6a678.png">

**Comment by efekankavalci** [comment]
I think your last update solves @acyishere's comment, I reviewed it as well. I am closing the issue.
