### ISSUE TITLE
Sequence Diagram: Enrollment in Course

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#126]
![Sequence Diagram Enrollment](https://user-images.githubusercontent.com/74719781/163274923-600cf54d-68b9-4323-afc4-d6f01c59d996.PNG)

Further review needed!

**Comment by omerozdemir1** [comment]
I reviewed your work. It seems nice, thanks for your effort.

**Comment by efekankavalci** [comment]
The title is mistakenly written as class diagram, I am changing it to Sequence Diagram. I also reviewed the your sequence diagram, I agree that it seems good.

**Comment by harunerkurt** [comment]
I checked, it seems good
