### ISSUE TITLE
Sequence Diagram: Sign Up

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#127]
Designed a sequence diagram for sign up.
![sequence](https://user-images.githubusercontent.com/73769340/163276804-81b57ba7-e277-4d8e-a06b-0b76e06721d5.png)
Review needed

**Comment by omerozdemir1** [comment]
I reviewed your work and can suggest one thing as an idea. You could have split 1 if-else part into 3 if-else part where each part is about username,password, and e-mail respectively.

**Comment by acyishere** [comment]
reviewed, it seems okay.
