### ISSUE TITLE
Sequence Diagram: Creating Subject on Forum

### ISSUE THREAD

**Issue by efekankavalci** [bounswe/bounswe2022group1#129]
As we discussed in the P.S., we have decided several topics for the sequence diagrams. I will design the topic "Creating Subject on Forum". In this direction, I will do the following:
- [x] Review the class diagram and use case diagram in the context of "Creating Subject on Forum"
- [x]  Make additions/changes in class diagram and use case diagram if necessary
- [x] Design the diagram on paper
- [x] Draw the diagram on LucidChart and look for review 

**Deadline:** 14.04.2022 Thursday 17.00

**Comment by efekankavalci** [comment]
I observed the lack of 'subject' term in the forum section of use case diagram and added include relations with the case of "choose subject", for the related cases. You can see it as follows:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/56485487/163283039-30b56fdd-4195-488a-ac77-c555d2d1c932.png">

**Comment by efekankavalci** [comment]
I reviewed the section in the class diagram regarding my sequence diagram topic, and decided to add a small 'Subject' class to the class diagram as a composition of 'Forum', in order to be more consistent. You can view it as follows: 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/56485487/163287265-59192f39-24e6-4c6c-8c2f-38ff10ea42be.png">

**Comment by efekankavalci** [comment]
I have prepared the sequence diagram as follows, I need reviewers to inspect it.
![Sequence diagram](https://user-images.githubusercontent.com/56485487/163287343-1405278e-1585-4bf2-a52a-8b47d5064cee.png)

**Comment by egetaga** [comment]
I reviewed the work and it seems pretty fine to me. Especially I liked the way you edit the class and use case diagrams to fully satisfy your needs. So far, it seems pretty good work to me. 

I believe it is a solid work. and I am closing the issue.
