### ISSUE TITLE
Sequence Diagrams: Follow User

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#132]
The task is to create a sequence diagram of the **following user scenario.** In order to complete the task, these steps should be followed.

- [x] Observe the form of the sequence diagrams from the examples
- [x] Write down the components and overall flow as a draft
- [x] Draw the sequence diagram using Lucidchart

`Deadline: 14.04.2022 19.00`

**Comment by ecesrkn** [comment]
The task is completed but needs review.
[Lucidchart link](https://lucid.app/lucidchart/ef99b8aa-45e7-4e2b-9e8c-104e18c58530/edit?invitationId=inv_34cce45c-f605-4a0e-bb99-57fb282b9f1c)

![image](https://user-images.githubusercontent.com/43001709/163399885-58a55ca9-6ae5-4e12-b3b4-73bd89fc0a95.png)

**Comment by mstfatay** [comment]
I rewieved it. It looks good. I am closing this issue.
