### ISSUE TITLE
Sequence Diagram: Taking a Note

### ISSUE THREAD

**Issue by kamilkorkut** [bounswe/bounswe2022group1#133]
I have created the sequence diagram for taking a note.

<img width="792" alt="Screen Shot 2022-04-14 at 13 47 44" src="https://user-images.githubusercontent.com/73702922/163377848-d73801dc-625d-4112-be1b-53765053ff2b.png">

Review is needed.

**Comment by mstfatay** [comment]
I reviewed it. It looks correct.

**Comment by efekankavalci** [comment]
I reviewed it too, it looks good.

**Comment by kamilkorkut** [comment]
There is not any error in the diagram based on reviews. So I am closing the issue.
