### ISSUE TITLE
Preparing Project Plan for 1st Milestone

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#136]
We have worked on project plan for 1st milestone. Further review essential!

**Comment by acyishere** [comment]
https://docs.google.com/document/d/1s-ov0__FLnRQ3AK3Bpvv3R_Bbs9-1xDmWdGLx1AwOp8/edit#

**Comment by omerozdemir1** [comment]
I think we should put the snapshot of our work on this issue.

**Comment by gecemavisioa** [comment]
![1](https://user-images.githubusercontent.com/73769340/163493935-3949cc20-41fc-4631-8466-dd4a751a5fd4.png)
![2](https://user-images.githubusercontent.com/73769340/163493940-c5ed139e-29b2-49e0-baef-00166f5b8b49.png)
