### ISSUE TITLE
Sequence Diagram: Searching Courses

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#137]
I will create the sequence diagram about searching a course. In order to achieve this task, I should consider following elements:

- [x] Checking class diagram to find related classes.
- [x] Thinking about methods that will take role.
- [x] Updating class diagram if I realize a problem due to my further thinking.
- [x] Finally, drawing the sequence diagram in Lucid Chart.

Deadline: 15.04.2022

**Comment by mstfatay** [comment]
Search_courses methot was missing in class diagram. I added it.

**Comment by mstfatay** [comment]
I created the diagram:
![search_courses](https://user-images.githubusercontent.com/46002371/163495236-0cb616c4-7dbd-47a9-965d-7680829fd1da.png)

Review needed!

**Comment by ecesrkn** [comment]
I reviewed the diagram, looks great! I'm closing the issue. @mstfatay
