### ISSUE TITLE
Adding Sequence Diagrams on Wiki Page

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#140]
`Purpose:` 
We have prepared some sequence and use case diagrams. However, we did not collect them in our [Sequence Diagram](https://github.com/bounswe/bounswe2022group1/wiki/Sequence-Diagrams) and [Use Case Diagram](https://github.com/bounswe/bounswe2022group1/wiki/Use-Case-Diagram) wiki pages. Please attach them into corresponding wiki page under corresponding category.

`Deadline:` 15.04.2022 22:00

**Comment by kamilkorkut** [comment]
I added [the sequence diagram for taking a note](https://github.com/bounswe/bounswe2022group1/issues/133) to the sequence diagram wiki page.

**Comment by egetaga** [comment]
I've added the sequence diagram for **retrieving statistics** to the [sequence diagram wikipage](https://github.com/bounswe/bounswe2022group1/wiki/Sequence-Diagrams).

**Comment by efekankavalci** [comment]
Use case diagram will be one part as whole in wiki page and M1 report as we discussed, therefore I am changing the title to solely sequence diagrams. I will upload the whole use case diagram to the wiki page.

**Comment by efekankavalci** [comment]
I added the sequence diagram for "Creating subject on forum" [here](https://github.com/bounswe/bounswe2022group1/wiki/Sequence-Diagrams#creating-subject-on-forum).

**Comment by efekankavalci** [comment]
I added the rest of the diagrams except the one of @kadirgokhann since his issue is not closed yet. After that one is done, we can close the issue.

**Comment by efekankavalci** [comment]
> I added the rest of the diagrams except the one of @kadirgokhann since his issue is not closed yet. After that one is done, we can close the issue.

I added his sequence diagram after his revision, therefore all of the sequence diagrams are on wiki page now.
