### ISSUE TITLE
Preparing responsibility assignment matrix

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#141]
We should prepare the RAM document such that everyone can fill in their contribution as "contributed", "lead", "reviewed", or "none".

Deadline: 15.04.2022 1 PM

**Comment by mstfatay** [comment]
I created a google sheets document to start working. Document is [here](https://docs.google.com/spreadsheets/d/1jIVuSU-u8po3wn22pMUTEkHA2WL4e1T8ytSm-51tT-w/edit#gid=0).

**Comment by ecesrkn** [comment]
I added the subcategories:

1. Communication and Infrastructure Setup
2. Customer Meeting
3. Requirements

and their respective responsibilities. Also, added the coloring code and did the formatting of the table.

**Comment by mstfatay** [comment]
I added the following subcategories and their responsibilities:

1. Scenario & Mockups
2. Software Design Documents In UML
3. Milestone 1 Report

I also reviewed the work done by @ecesrkn. It looks good.

**Comment by ecesrkn** [comment]
I reviewed your part as well @mstfatay I think we can share the document with the team now. I'm closing the issue.
