### ISSUE TITLE
Sequence Diagram: Retrieve Statistics 

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#145]
The lecturers shall be able to display their relevant statistics. It should be remembered that the statistics are related to the courses given by the lecturer. Therefore, it is pretty possible that the lecturer has no statistics yet. In that case, the system and the system database should return a message showing the non-existence of the statistics. 

The sequence diagram for retrieving statistics should be prepared considering these points. 

Deadline: 15.04.2022

**Comment by egetaga** [comment]
By considering the above points, I prepared a sequence diagram implementing all of the above mentioned functionalities.

- The system database queries whether there is relevant statistics and returns error message or statistics depending on the query.
- It seems fine to me now, but before closing the issue I need further review from the team mates. 
![Sequence diagram-2](https://user-images.githubusercontent.com/42147612/163547817-132cc9a1-d4d0-4281-bbea-8eaed8c82d65.png)

**Comment by efekankavalci** [comment]
I reviewed your work and, I think the sequence diagram illustrates the point you mentioned well. Therefore, I am closing the issue.
