### ISSUE TITLE
Adding Notes of Meeting 1

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#15]
We should summarize what we talked in the discussion.

**Comment by kadirgokhann** [comment]
I added the notes I took during the discussion, and the participants.

**Comment by ecesrkn** [comment]
https://github.com/bounswe/bounswe2022group1/issues/9 issue already created

**Comment by ecesrkn** [comment]
I edited the page so now it has the proper format using the terms introduced in the first lecture. Also, added action items table.
