### ISSUE TITLE
Editing Homepage wiki

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#156]
Description
A lot of work has been done so far, but there is very little information on the main wiki page. It is necessary to add the works done to the main wiki page named Home.

**Comment by harunerkurt** [comment]
I added

- Communication Plan Section
- Requirements Section
- Research Section (removing favorite github repositories heading)
- Scenarios and Mockups Section
- Diagrams Section

**Comment by harunerkurt** [comment]
You can close the issue after reviewing

**Comment by mstfatay** [comment]
I checked every link you added. There is no problem with links. Layout looks good too. I am closing this issue.
