### ISSUE TITLE
Evaluation of Deliverables

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#157]
Deliverables should be evaluated.

- Project Repository
- Communication Plan
- Researches for Git and Github
- Requirements and Glossary
- Scenarios and Mockups
- Software Design Documents in UML
- Class Diagram
- Use Case Diagram
- Sequence Diagram
- User Personas and Stories
- User Scenarios and Mock-ups
- Project Plan
- RAM

**Comment by harunerkurt** [comment]
I added my evaluation to docs

We use a GitHub repository as the main workspace for the collective and collaborative work. Our project repository is named bounswe2022group1 and there are 10 team members who are contributing to the repository.

When you first enter the repo, the reademe.md file welcomes you. Readme.md file consists of an introduction, team members, brief about cmpe352 course, instructor and TAs.

We use wiki structure to document our research and the work that needs to be done. There is a homepage named Home in our wiki. Homepage shows our picture at first, then shows team members with personal wiki page links. Homepage also shows meeting notes, communication plan, requirements, researches, scenarios, mockups and diagrams with links to their wiki pages. In our wiki page there is a sidebar to access pages easily.

**Comment by kadirgokhann** [comment]
Reviewed. Everything is perfect.
