### ISSUE TITLE
Milestone1: List and Status of Deliverables

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#159]
All deliverables should be determined and related table created.

You can close this issue after reviewing.

**Comment by harunerkurt** [comment]
I created the section and added the table. You can check this [doc](https://docs.google.com/document/d/1s-ov0__FLnRQ3AK3Bpvv3R_Bbs9-1xDmWdGLx1AwOp8).

**Comment by kadirgokhann** [comment]
Reviewed. Nothing to change.
