### ISSUE TITLE
Sequence Diagram: Create Course

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#160]
The squence diagram for creating course will be drawn with the help of the related classes methods and user.

User wants to make a create course ,
After succes of create course, user add course ,
After succes of add course, course added user's course list.

**Comment by harunerkurt** [comment]
<img width="693" alt="Ekran Resmi 2022-04-15 17 21 55" src="https://user-images.githubusercontent.com/49256548/163582343-4516b309-55f4-4be0-8799-27c41b97bd4d.png">

**Comment by acyishere** [comment]
reviewed, timeline and activities are in place. Closing the issue
