### ISSUE TITLE
Sequence Diagram: Creating Events

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#161]
The sequence diagram for creating events should be created with the help of the related classes.

User wants to create an event for some course
First we check if user is lecturer of the course
if he/she is, then create the event
add created event to the events list of a course
if event is private notify the invited participants

**Comment by harunerkurt** [comment]
<img width="842" alt="Ekran Resmi 2022-04-15 17 22 08" src="https://user-images.githubusercontent.com/49256548/163582758-9d2de4ff-03fe-404d-8cf1-98849af39925.png">

**Comment by acyishere** [comment]
reviewed, timeline at the  end for feedbacks may need a revision

**Comment by kadirgokhann** [comment]
Reviewed.  You may return true or false instead of using OK.
