### ISSUE TITLE
We should decide on our meeting template

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#17]
We should have a nice template for the meeting reports of each week. I have found the following template from previous years. I have modified the first meeting's report according the following template.  Does anyone has a suggestion or better idea about it? 

```

This is the report of  first/second/... meeting

Date: ../../..
Location: Online/Face to Face
Topic/Reason of Meeting : ....
Attendees:
Main Points of Meeting:
Results:
```

**Comment by ecesrkn** [comment]
Using terms like "Agenda" "Discussions" and "Action Items" sounds more professional and it is also mentioned during the lecture.

**Comment by ecesrkn** [comment]
The template agreed on is the one we used for the[ first meeting notes](https://github.com/bounswe/bounswe2022group1/wiki/Meeting-%231-(03.03.2022))
