### ISSUE TITLE
Editing labels

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#19]
Some labels are written twice, uppercase lowercase letters should be edited. Labels should be made more structured.

**Comment by kadirgokhann** [comment]
They are disorganized. Should be more structured. I assigned to me because i want to follow and control  this situation.

**Comment by harunerkurt** [comment]
Duplicate labels deleted. Labels are categorized. Edited with attention to capitalization. Colors may need to be recreated.

**Comment by kadirgokhann** [comment]
One more review from someone else can be helpful.

**Comment by omerozdemir1** [comment]
We have added necessary labels. Everyone has agreed with the harmony of the current labels with our github repo.
