### ISSUE TITLE
Reviewing Use Case Diagram and changes

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#211]
For the Practice Application Learning Platform, @mstfatay has prepared the initial draft version of the Use Case diagram, which can be checked in [there](https://lucid.app/lucidchart/6f93567b-1da6-424a-b95f-2a4440c25a1f/edit?invitationId=inv_64879bdf-91bb-4ddf-af2b-958fa5c34bc3&page=y.Ih0OXa.4pY#). 

- I will add and contribute to the diagram. 
- Review whether its design is correct. 
- Fix the problematic parts. 
- Add some use cases.

**Comment by egetaga** [comment]
I extended **Specify Preferences** and **Delete Course** use cases. 

-  I added **Add a preference** use case extending **Specify Preferences**. 
- I added **Recover the change** use case extending **Delete Course**.
- If no more changes will be made, I will close the issue. 
- - The final form is as follows: 
- 
![Screen Shot 2022-05-19 at 19 11 51](https://user-images.githubusercontent.com/42147612/169347882-74b0b99e-e1fa-45e4-b05b-1fd4885a4833.png)

**Comment by efekankavalci** [comment]
I reviewed the diagram,  I think it looks good. A minor issue is the 'extend' relation is written erroneously as 'extent', I will fix them and I will also think about how we can detail it more.

**Comment by efekankavalci** [comment]
I corrected the extend relations and added two include relations for give rate.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/56485487/169352629-6e0c7f7a-79ad-44bf-b1dc-fd2eebe7efe3.png">
