### ISSUE TITLE
Communication Plan

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#22]
I think we have decided these.  Is there any URL that one can see the answers?

Prepare your communication plan and document it on your GitHub repository's Wiki pages. Your
plan should include the following information with the following in each row:
- Who will participate
- Where (i.e. department, Doydos, skype, slack, ...)
- Purpose (i.e. progress update)
- When (i.e. Mondays at 5)
(from the document on moodle)

**Comment by kadirgokhann** [comment]
Also, we need an URL of communication plan.

**Comment by kadirgokhann** [comment]
Creted the URL and added to the navigator.

**Comment by kadirgokhann** [comment]
Added the icon.

**Comment by kadirgokhann** [comment]
Can you check [link](https://github.com/bounswe/bounswe2022group1/wiki/Communication-Plan) ?

**Comment by ecesrkn** [comment]
I think it looks great 👍  We can always update it if something comes up along the way. (If want to switch to another platform or do subgroup tasks in the next weeks.)

**Comment by mstfatay** [comment]
I reviewed it, it looks good. I think we can close this issue.
