### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#23]
A label "About Wiki" or just "Wiki" should be added, which means the issue is about the documentation on Wiki. Is there any option to use it?

**Comment by harunerkurt** [comment]
Labels should not specify so much detail. too many labels make labels useless.

**Comment by kadirgokhann** [comment]
Does anyone have another idea in this topic? Should we have more labels describing which part of the github it is related? 

We can use those labels together; 'Low Priority' & 'Wiki' or  ''High Priority '  & 'Project'.
We need comments and ideas.

**Comment by harunerkurt** [comment]
This issue is beyond the purpose of the issue system. This issue contains conversation. This topic should be discussed on a different platform
