### ISSUE TITLE
Preparing project plan for milestone 2

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#254]
We need to prepare our project plan.
`Deadline: 23:00`

**Comment by gecemavisioa** [comment]
We prepared the project plan.
![PPlan](https://user-images.githubusercontent.com/73769340/169600207-32fb0f24-b6ba-4689-b294-d588217fa619.png)
![PPlanTime](https://user-images.githubusercontent.com/73769340/169600215-c3580953-0574-405b-8c85-a73cb94cad83.png)

**Comment by acyishere** [comment]
reviewed. Perfect.
