### ISSUE TITLE
Sequence Diagrams: Student My Courses

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#265]
I have uploaded sequence diagrams of Student My Courses APIs to the related wiki page. [(see)](https://github.com/bounswe/bounswe2022group1/wiki/Sequence-Diagrams-for-the-Practice-App
![seq-get](https://user-images.githubusercontent.com/73769340/169602988-4637dfde-7d30-4e22-9961-690a1ba48e6e.png)
![seq-post](https://user-images.githubusercontent.com/73769340/169603005-658acfb3-a934-4275-ba71-bb8da1b8f703.png)
)

**Comment by acyishere** [comment]
reviewed. Decent.
