### ISSUE TITLE
Who checks what?

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#281]
Based on the talk after the PS(4.10.2022), these pages need to be checked by the person.
Deadline: 09.10.2022

<google-sheets-html-origin>

Member | Task
-- | --
Everyone | Personal Pages
Kadir Kalkan | Project Briefing
Ege | Glossary Requirements
Mustafa Ömer | Fundamental Features
Ege / Ömer | Semantic Search
Kadir G | GDPR Rules
Kadir G | KVKK Rules
Ahmet YAZICI, Ece Sarkın | W3C Web Annotation Data Model
Harun | W3C Standarts
Hüseyin Seyyid | W3C Geoinfo
Osman / Kadir K | Class Diagram
Ahmet | Sequence Diagrams
Ece | Use Case Diagram
Kadir K | Mockups
Ahmet / Ömer / Osman / Kadir K. | Porject Libre File
Kadir G | Communication Plan
  | Responsibility Assignment Matrix
Kadir G | Homepage
Kadir K. | İssue template

**Comment by acyishere** [comment]
Reviewed the W3C Web Annotation Data Model and will share the improvements on lab sessions.

**Comment by kadirgokhann** [comment]
They are all okey.
