### ISSUE TITLE
Repository Contributors

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#282]
There are lots of people in the contributors. We know that some have changed during the summer. Is the user list as it should be?

**Comment by alper111** [comment]
Just to make sure, these are not currently in your team, right? I will remove them after confirmation.
- [ ] Elif Akalin
- [ ] Efekan Kavalci
and I believe `acyishere` is Ahmet Cemil Yazici. Anyone else?

**Comment by egetaga** [comment]
Yes, both Elif and Efekan are not in our team anymore. You could remove them safely @alper111. And yes you are right, acyishere is Ahmet Cemil Yazıcı.

**Comment by kadirgokhann** [comment]
Based on this issue, i will change the homepage.
