### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#289]
**Issue Description:**

Add a description of the issue

**Tasks to Do:**

- [x] #313
- [x] add reviewer
- [x] #314

*Task Deadline:* 11.10.2022 13.00

*Final Situation:*

The issue template can be seen [here](https://github.com/bounswe/bounswe2022group1/issues/289)

*Reviewer:*  @kkadirkkalkan 

*Review Deadline:* 11.10.2022 15.00

**Comment by kadirgokhann** [comment]
Looks good.

**Comment by acyishere** [comment]
Decided on
