### ISSUE TITLE
Reviewing the Class Diagram

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#290]
I revised the class diagram and updated the related page. Final version of the class diagram can be seen [here](https://github.com/bounswe/bounswe2022group1/wiki/Class-Diagram).

**What has changed?**
1. Fixed a few typos:
    ![typo 1](https://user-images.githubusercontent.com/73769340/194865501-f331254a-a865-4d7e-a49d-420bb5aaf30a.png)
2. Since most of the fields are related with its own class, changed unnecessarily public fields to private. Added getters and setters accordingly:
Half of the classes had public fields, therefore I cannot add them all here. The image below is just one example.
  ![pubtopriv](https://user-images.githubusercontent.com/73769340/194867292-40e3e18a-e3b9-4112-89b5-7413894349cb.png)
3. Removed get_text method of the Annotations abstract class since the text field belongs only the Annotation Text class:
  ![getter](https://user-images.githubusercontent.com/73769340/194869569-e000ed44-6a35-40e1-a3b7-393f802530bf.png)
4. Arranged all classes according to the convention for increasing readability:
Rewrote userId and other fields highlighted with green according to snake_case. Changed "->" marks to ":". Again for the sake of readabilty, added blank spaces as needed.
  ![convold](https://user-images.githubusercontent.com/73769340/194870976-41dbe130-7f43-4552-9644-df98799bfeb7.png)

Other than these, the class diagram seems appropriate to the requirements and the project.

**Comment by omerozdemir1** [comment]
Wow! Good job!
I saw the changes on [Class Diagram](https://user-images.githubusercontent.com/73769340/194870657-56fe3995-43da-4773-816c-41be7aef63e9.png) that you have done. Seems fine.
