### ISSUE TITLE
Reviewing the Use Case Diagram

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#292]
Issue Description:

Review the Use Case diagram and update necessary features.

Tasks to Do:

- [x]   review the updates on the class diagram 
- [x]   revise the use case diagram in accordance with the updated version of the class diagram

Task Deadline: 11.10.2022 13.00

Final Situation: [Final version of the use case diagram](https://github.com/bounswe/bounswe2022group1/wiki/Use-Case-Diagram)

Reviewer: @egetaga 

Review Deadline:  13.10.2022

**Comment by ecesrkn** [comment]
To remember the use case diagram relationships, I have read this [page](https://creately.com/blog/diagrams/use-case-diagram-relationships/). Some notes that I've made:
**Extends**:
(Extended/Base) <--<\<extends\>>--- (Extending)
The extending use case is usually optional, dependent on the base. The base is meaningful on its own.
**Includes**:
(Including/Base) --<\<includes\>>--> (Included)
The base is incomplete without the included use case. Included is mandatory, not optional.

**Comment by ecesrkn** [comment]
Some arrows should be reversed to be meaningful. 
1. <img width="425" alt="image" src="https://user-images.githubusercontent.com/43001709/195003386-a4a52b3e-11a3-4c58-9090-fc60fe2404b2.png">
Base and extending use cases should be switched.

2.  
<img width="425" alt="image" src="https://user-images.githubusercontent.com/43001709/195003552-c260d239-7d62-49ff-8512-dd4e82cda34b.png">
should be "includes" with the same direction

3.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/43001709/195004243-e29d1c63-5367-4b07-874a-752eb66f8cd5.png">
Replying to a specific message should be optional. Thus the relationship should be "extends".

4.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/43001709/195004441-3d5a1a0c-d233-4a3e-9e79-b03567c72f16.png">
Includes arrow directions should be reversed.

5.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/43001709/195004618-8dd61c78-29ae-4999-8e25-6f4e6979ed1b.png">

All arrows should be extends with the base use case "View Events"

6.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/43001709/195004958-acd2f690-790c-4a6d-9edb-5412a77a9573.png">
This relationship should be "extends" with the "Update Event" use case being the base.

**Comment by ecesrkn** [comment]
The updated version is available [here](https://github.com/bounswe/bounswe2022group1/wiki/Use-Case-Diagram). A review is needed.

**Comment by egetaga** [comment]
Reviewed and it seems all fine to me. Thanks for your corrections, these were seemingly minor mistakes but would be very problematic in the implementation.
