### ISSUE TITLE
Correcting the ambiguity on the issue #281

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#296]
**Issue Description:**

We have the same name as our new member Kadir Kalkan. I didn't add the last name to some of them while assigning the tasks. That's why I fixed which Kadir they are

**Tasks to Do:**

- [x] Fix the names

*Task Deadline:* 11.10.2022 13.00
*Final Situation:*
Completed [#281](https://github.com/bounswe/bounswe2022group1/issues/281) 

*Reviewer:*  @ecesrkn 

*Review Deadline:* 11.10.2022 15.00

**Comment by ecesrkn** [comment]
It seems that the ambiguity is resolved. I'm closing the issue.
