### ISSUE TITLE
Adding (Communicator) in the front page next to Ege Onur Taga

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#299]
**Issue Description:**

Last week, we got a feedback saying that we should update our front page to show who is the communicator evidently.

**Tasks to Do:**

- [x] Update the front page by adding (Communicator) next to Ege Onur Tağa

*Task Deadline:* 11.10.2022 13.00

*Final Situation:* 

*Reviewer:* Not needed

*Review Deadline:* Not needed

**Comment by egetaga** [comment]
I updated the page and sent a pull request. The pull request can be found [here](https://github.com/bounswe/bounswe2022group1/pull/300). A review is needed to merge the pull request.

**Comment by kadirgokhann** [comment]
Can you review the comment I posted in your PR?

**Comment by egetaga** [comment]
I reviewed and closed the PR with this message: 

> Thought since we had a class today and it was still not done, I added communicator next to myself. Since you opened up 
> another PR, I am approving it and closing this PR
