### ISSUE TITLE
Creating and customizing personal wiki pages

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#3]
We should create and customize our own wiki pages by adding information regarding our skills, personal URL's, addresses, and some text describing ourselves.

**Comment by kadirgokhann** [comment]
Completed.

**Comment by harunerkurt** [comment]
I created my own personal wiki page

**Comment by egetaga** [comment]
Done by me

**Comment by elxif** [comment]
Done.

**Comment by mstfatay** [comment]
Completed

**Comment by quanex1** [comment]
Completed

**Comment by acyishere** [comment]
completed

**Comment by efekankavalci** [comment]
Completed.

**Comment by ecesrkn** [comment]
Done my part

**Comment by kamilkorkut** [comment]
completed

**Comment by egetaga** [comment]
I recustomized my weekly efforts part. Closing the issue for now.
