### ISSUE TITLE
Rewieving Communication Plan

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#301]
**Issue Description:**

Since we are no longer in the online period, we had to make changes in the communication plan. Necessary changes were made according to the speeches in the first lesson.

**Tasks to Do:**

- [x] Correcting the communication polan

*Task Deadline:* 11.10.2022 13.00

*Final Situation:*

The result is - [Communication Plan](https://github.com/bounswe/bounswe2022group1/wiki/Communication-Plan)

*Reviewer:*  @egetaga 

*Review Deadline:* 11.10.2022 15.00

Related Links:
-

**Comment by egetaga** [comment]
We have decided to communicate asynchronously with the team members most of the time. So, we decided to use discord and create channels for specific roles, such as back-end and front-end. This was missing in the plan, so I added it accordingly. The new communication plan is as follows: 
<img width="961" alt="Screen Shot 2022-10-11 at 11 42 04" src="https://user-images.githubusercontent.com/42147612/195042276-d16f5e15-f231-48d2-8ea2-d6f88370709e.png">
