### ISSUE TITLE
Rewieving the Homepage

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#303]
**Issue Description:**

Since we started a new era, there were still traces of 352 on our homepage. In addition, our TAs have also changed. I have completed the change of Homepage. I emphasized that @egetaga  is a communicator. I made a PR request, but then I learned that @egetaga  did the same. After communication with Ege, we may close his PR and activate my PR.

**Tasks to Do:**

- [x] Correcting the [Homepage](https://github.com/bounswe/bounswe2022group1)

*Task Deadline:* 11.10.2022 13.00

*Final Situation:*

It is corrected and sent a [PR](https://github.com/bounswe/bounswe2022group1).

*Reviewer:*  @egetaga 

*Review Deadline:* 11.10.2022 15.00

**Comment by egetaga** [comment]
I did review your PR and no conflicts or problems whatsoever. Closing this issue. Thanks for your efforts :)
