### ISSUE TITLE
Meeting with the Android team

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#311]
`Description:` We will held a meeting today at 20:00 to discuss what technologies we will use and how we will progress throughout the semester.
`Deadline`: 14.10.2022 - 20:00
`Location:` Zoom

**Comment by omerozdemir1** [comment]
- The meeting is done.
- We decided to use Pixel 3a API 29.
- We created a new branch called androd_main.
- Each of us cloned the android_main branch. 
- We made a sign-in app to get used to Android Studio.
- Everyone downloaded Android Studio and Pixel 3a API 29 Emulator.
- The meeting took 4 hours. (20:00-24:00)
- Everyone in the Android Team participated into the meeting.
- Everyone deleted Android SDK except version 10.
- Everyone decided to start learning Android Studio starting from now on.

**Comment by harunerkurt** [comment]
The notes we took and what we did were written exactly in the previous comment. There are no errors.
