### ISSUE TITLE
We need labels like Frontend,Backend, etc.

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#321]
**Issue Description:**

It would be very useful to have labels where we can show them instead of writing a frontend to title of each issue.

**Tasks to Do:**

- [x] adding labels

*Task Deadline:* 20.10.2022 13.00

*Final Situation:*

Frontend,Backend and Mobile are added.

*Reviewer:*  @kkadirkkalkan 

*Review Deadline:* 20.10.2022 15.00

Related Links:
None
Final Actions:
None

**Comment by hseyyidkaplan** [comment]
simple but important contribution

**Comment by kkadirkkalkan** [comment]
Labels are added so I am closing the issue.
