### ISSUE TITLE
Meeting with the backend team

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#323]
Issue Description:

As a backend team, we have decided to implement a simple running Django app written with respect to good Django conventions. For this task, we decided to meet on 17.10.2022, at 10.30 pm.  

**Tasks to Do:**
- [x]  Meet with @mstfatay, @kkadirkkalkan on 17.10.2022, at 10.30 pm.
- [x] Implement a simple running Django App before the PS on Tuesday. 

*Task Deadline:* 18.10.2022 15.00

*Final Situation:*

*Reviewer:*  @mstfatay 

*Review Deadline:* 18.10.2022 15.00

**Comment by egetaga** [comment]
On 17.10.2022, at 10.30 pm we have met as a backend group, consisting of @mstfatay, @kkadirkkalkan  and me. We together finished the first two section's implementation and created a simple project, which we believe may help in implementing the OLP until the first deadline.

**Comment by mstfatay** [comment]
It was nice to meet with the team!
