### ISSUE TITLE
Group Mail

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#324]
**Issue Description:**

Based on the [#308](https://github.com/bounswe/bounswe2022group1/issues/308), we need an email on gmail. 

**Tasks to Do:**

- [x] create an email

*Task Deadline:* 20.10.2022 13.00

*Final Situation:*

Created .
cmpe451.group1@gmail.com

*Reviewer:*  @mstfatay 

*Review Deadline:* 20.10.2022 15.00

Related Links:

Final Actions:
@mstfatay shall add courses our account which is created with our email.
All members should say which course they want to be added.

**Comment by kadirgokhann** [comment]
As a frontend, we need https://www.udemy.com/course/react-redux-egitimi/

**Comment by ecesrkn** [comment]
This course could also be useful. https://www.udemy.com/course/react-the-complete-guide-incl-redux/learn/lecture/25595342?start=0

**Comment by mstfatay** [comment]
Thanks for this issue. I will add those courses to this Udemy account in another issue.
