### ISSUE TITLE
Upload meeting notes #2

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#33]
Upload meeting notes of week 2 on our wiki page

**Comment by kadirgokhann** [comment]
I'm sorry that i couldn't attend the meeting since my family problems. Could you also mention this in the notes?

**Comment by ecesrkn** [comment]
> I'm sorry that i couldn't attend the meeting since my family problems. Could you also mention this in the notes?

sure!

**Comment by ecesrkn** [comment]
Completed the task [Meeting Notes #2](https://github.com/bounswe/bounswe2022group1/wiki/Meeting-Notes-%232-(09.03.2022))
