### ISSUE TITLE
Issue Template V2

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#330]
**Issue Description:**

We are using this template method thanks to @kkadirkkalkan, but @alper111  has promised to create an automated issue system for us. The deadline is **strictly strict** and cannot be exceeded.

**Tasks to Do:**

- [ ] search for the issue template system
- [ ] create one of them for us

*Task Deadline:* 20.10.2022 13.00

*Final Situation:*

-

*Reviewer:*  @kadirgokhann  

*Review Deadline:* 20.10.2022 13.05

Related Links:

https://github.com/pytorch/pytorch

Final Actions:

- Teach us how to use it.

**Comment by alper111** [comment]
Added your suggested issue template and GitHub's default issue templates.

**Comment by kadirgokhann** [comment]
I reveiwed it, thank you @alper111 .
