### ISSUE TITLE
Creating an Authentication Page with React.js

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#336]
****Issue Description:****

I will create Login and Signup Pages for authentication to the platform. This will provide to control course enrollment and personal account.

**Tasks to Do:**

- [x] add issue labels
- [x] add reviewer
- [x] add new branch for task
- [x] commit changes

*Task Deadline:* 27/10/22 20:00

*Final Situation:* Related pages that I mentioned was added and pushed to the newly created branch.

*Reviewer:* @kadirgokhann @ecesrkn @kamilkorkut 

*Review Deadline:* 30/10/22 23:59

**Comment by hseyyidkaplan** [comment]
I have done this task, I would you to review my changes dear teammates: @ecesrkn @kadirgokhann @kamilkorkut

**Comment by ecesrkn** [comment]
Great work, thanks Huseyin! I'm closing the issue.
