### ISSUE TITLE
Ömer Özdemir will research the concepts mentioned in the project

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#34]
There are some concepts mentioned in the description of the project like "**semantic searching**". I will do some research about it. When my research is done, I will put what I have learned about them into our [Research](https://github.com/bounswe/bounswe2022group1/wiki/Research). Then, I will close the issue.

**Comment by egetaga** [comment]
Research about **"Semantic Searching"** and similar terms does not belong to [Git Research Page](https://github.com/bounswe/bounswe2022group1/wiki/Git-Research). They require another distinct wiki.  You may edit your issue description.

**Comment by omerozdemir1** [comment]
I am closing the issue because I will open another issue which will be well organized and to the point.
