### ISSUE TITLE
Organizing The Folder Structure

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#352]
**Issue Description:**

I will organize the folder structure so that all teams (backend, frontend, android) can work together. I will init the folders with dummy files and leave the rest to the teams.

**Tasks to Do:**

- [x] update folder structure

*Task Deadline:* 
25.10.2022 17:00

*Final Situation:*

*Reviewer:*  
@omerozdemir1 

*Review Deadline:*
25.10.2022 18:00

**Comment by omerozdemir1** [comment]
I reviewed your work and it seems good. Now, as Android team, we are trying to sync ourselves with the new folder structure.
