### ISSUE TITLE
We should specify the requirements of the project

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#36]
`Purpose:` Listing the requirements of the project like [Student Requirements](hyperlink) and [Teacher Requirements](hyperlink)
`Deadline:` Each meeting we will decide on whether the requirements are done or not. If it is done, then this issue will be closed.

**Comment by mstfatay** [comment]
We decided that requirements are done so far. Therefore, I am closing this issue.
