### ISSUE TITLE
Request to use Issue Panel

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#361]
**I couldn't use the issue panel on the right side (Assignees, Labels, Projects, etc.) while I open a new Issue.**

I request you to open this features to me since this enhances and clarifies an Issue.

*Assignee: @alper111* 

<img width="271" alt="Ekran görüntüsü_20221023_165231" src="https://user-images.githubusercontent.com/32467338/198249124-34c93d90-035f-46c7-92aa-f1313244867f.png">

**Comment by alper111** [comment]
OK, this is because you have not accepted my previous invitation to bounswe organization. I have re-send the invitation.

**Comment by hseyyidkaplan** [comment]
Same comment as: https://github.com/bounswe/bounswe2022group1/issues/363#issuecomment-1296233403
