### ISSUE TITLE
Permission Request for Pushing Commits to GitHub

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#363]
**I haven't got any permissions for pushing commits to our GitHub repository.**

As it can be seen below figure, I couldnt push my commits to GitHub because I don't have permission to do such an action. Could you check it please @alper111 ?

- [ ] give permission to user: hseyyidkaplan

*Final Situation:*  

*Assignee: @alper111*  

<img width="339" alt="image" src="https://user-images.githubusercontent.com/32467338/198364922-11e50236-498e-4bff-a870-02db2c3470d7.png">

**Comment by hseyyidkaplan** [comment]
I guess, due to the same reason, I couldn't add any new branch.
![image](https://user-images.githubusercontent.com/32467338/198369128-9fdbf887-2ddd-4d22-b518-009f8283b508.png)

**Comment by alper111** [comment]
The same as #361. You should have done this earlier...

**Comment by hseyyidkaplan** [comment]
I got message from you in 3rd October and I assumed I accepted the invitation but it seems I couldn't. Anyway, thanks.
