### ISSUE TITLE
Implementing register functionality

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#370]
**Issue Description:**

Register, login, logout and change password functionalities should be implemented.

**Tasks to Do:**

- [ ] Implement register functionality

*Task Deadline:* 
29.10.2022 15.00

*Final Situation:*
I have learned how to implement this functionality

*Reviewer:*  @egetaga 

*Review Deadline:*
29.10.2022 15.00

**Comment by egetaga** [comment]
I did implement login, logout and change password functionalities, together with the unit tests of register, login and logout. I have seen that you also implemented register. So, I am closing the issue, since there is nothing left.

**Comment by kkadirkkalkan** [comment]
I followed this [tutorial](https://studygyaan.com/django/django-rest-framework-tutorial-register-login-logout) and implemented register functionality. I used Django Rest Knox library in order to implement token based authentication system.
