### ISSUE TITLE
Frontend: Group meeting

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#389]
**Issue Description:**

Group meeting with @hseyyidkaplan . It last 1 hour. I showed him what i have done so far.

**Comment by hseyyidkaplan** [comment]
Yes, it was very enlightening and helpful meeting. Kadir showed me newly adapted code structure and how to sync when authorizing to BUDEMI by using APIs. We also learned some GitBash terminal features and commiting conventions.
