### ISSUE TITLE
Frontend: Content of the Homepage

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#394]
**Issue Description:**

The texts and photos in the components on the site have been made meaningful and smooth.

**Tasks to Do:**

- [x] change pictures
- [x] change texts

*Reviewer:*  @hseyyidkaplan 

*Review Deadline:* 01.11.2022

**Comment by hseyyidkaplan** [comment]
Could you add a link so I can follow the changes?
