### ISSUE TITLE
Creating a "fundamental features with referances" page

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#42]
We should create a page that lists the requiered features. This is needed for us to referance a feature easily in future. This page doesn't need to include further information about features, simple feature names should be enough.

**Comment by omerozdemir1** [comment]
I have created [a new page](https://github.com/bounswe/bounswe2022group1/wiki/Fundamental-Features-of-the-Project) for it.

**Comment by mstfatay** [comment]
I added the page to navigator.

**Comment by mstfatay** [comment]
Finished the page by meeting in-person with @omerozdemir1. We decided to use flat table structure for subtopics and did everything can be well referanced with topic numbers.

**Comment by omerozdemir1** [comment]
I reviewed the feature page, it seems great!
