### ISSUE TITLE
Frontend: Token on local storage 

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#433]
**Issue Description:**

I designed and implemented the system about where to store the token that returns to us when we log in and how to use it later.

<img width="572" alt="Screen Shot 2022-10-31 at 23 51 43" src="https://user-images.githubusercontent.com/74508086/199108164-3ff9c33f-4f28-42d3-8859-5e79253a1050.png">

**Tasks to Do:**

- [x] store token

*Reviewer:*  @ecesrkn 

*Review Deadline:* 01.11.2022 15:00

**Comment by ecesrkn** [comment]
Message code "adsad" does not look user-friendly, but looks and works alright in general!
