### ISSUE TITLE
Scenario & Mockups - Android Team

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#438]
**Issue Description:**

We are handling the Scenario & Mockup process for Android App

**Tasks to Do:**

- [ ] Creating Scenario & Mockup in [Scenario & Mockups]( https://docs.google.com/presentation/d/1olqlo-6WmfHeJYwe8aOJy51TaTVHMcjySxg96oAybeo/edit#slide=id.g17afaf87c36_3_14)

*Task Deadline:* 
01.10.2022
*Final Situation:*
In progress
*Reviewer:*  
@acyishere @harunerkurt @omerozdemir1 
*Review Deadline:*
01.10.2022

**Comment by harunerkurt** [comment]
It looks fine.
