### ISSUE TITLE
Sign in page for Android App

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#439]
**Issue Description:**

Login page is required for android app.

**Tasks to Do:**

- [x] login page design
- [x] writing codes for buttons

*Task Deadline:* 

22.09.2022

*Reviewer:*  @gecemavisioa 

*Review Deadline:* 23.09.2022

**Comment by harunerkurt** [comment]
Design and page are created. the page works fine

**Comment by gecemavisioa** [comment]
Seems good!
