### ISSUE TITLE
Backend - Project Plan

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#459]
**Issue Description:**

I will create a project plan for the backend team and link it to the milestone 1 report.

**Tasks to Do:**

- [x] create project plan
- [x] link it to milestone 1 report

*Task Deadline:* 
01.11.2022 10:00

*Final Situation:*
Project plan for backend team is [here](https://github.com/bounswe/bounswe2022group1/wiki/Project-Plan-for-Backend-Team)

*Reviewer:*  
@egetaga @kkadirkkalkan 

*Review Deadline:*
01.11.2022 11:30

**Comment by kkadirkkalkan** [comment]
The project plan is created. Therefore, I am closing this issue.
