### ISSUE TITLE
Specifying date and time for the meeting with the customer

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#46]
We should allocate a specific date and time for our first meeting with the customer. For this, we should communicate with the customer and find a suitable time slot for both parties. Also we should wait until all our [questions](https://docs.google.com/document/d/1UsrRIajmg04a8xFbAvqZjcEeNq2-YA7hB8PDrr_qWqE/edit) are prepared for the requirement elicitation. 
- Deadline: 17.03.2022
- The issue will be closed if specific date and time is allocated to us by the customer.

**Comment by elxif** [comment]
We've had our customer meeting today at the Problem Session.
