### ISSUE TITLE
Meeting with Ece, and Kadir Gökhan Sezer on helping them frontend deployment

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#462]
**Issue Description:**

Although not again my responsibility, the frontend team didn't finish their project, especially the deployment part and didn't dockerized it yet. I will be helping @ecesrkn and @kadirgokhann on these parts. We couldn't reach @kamilkorkut and @hseyyidkaplan yesterday and today on the matter, while their functionalities are not working. 

**Tasks to Do:**

- [x] Help deploying the frontend project

*Task Deadline:* 1.11.2022

*Final Situation:* In progress

*Reviewer:*  -

*Review Deadline:* -

**Comment by kadirgokhann** [comment]
I waited for the friends to finish their projects yesterday, then I would go to the deploy part. I guess they didn't finish, they didn't even say they wouldn't finish it, so it wasn't deployed. In the morning, Ege came to the aid early and helped the deployment part.

**Comment by egetaga** [comment]
I did deploy their app on http://3.83.31.5:3000
Unfortunately, It doesn't work properly. But I did help them and now closing the issue.

**Comment by hseyyidkaplan** [comment]
> **Issue Description:**
> 
> Although not again my responsibility, the frontend team didn't finish their project, especially the deployment part and didn't dockerized it yet. I will be helping @ecesrkn and @kadirgokhann on these parts. We couldn't reach @kamilkorkut and @hseyyidkaplan yesterday and today on the matter, while their functionalities are not working.
> 
> **Tasks to Do:**
> 
> * [x]  Help deploying the frontend project
> 
> _Task Deadline:_ 1.11.2022
> 
> _Final Situation:_ In progress
> 
> _Reviewer:_ -
> 
> _Review Deadline:_ -

Yes, it was not your reponsibility.
