### ISSUE TITLE
Reviewing the Issues

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#463]
**Issue Description:**

I will review the issues which are opened by @kadirgokhann
Related Issues are: 
[https://github.com/bounswe/bounswe2022group1/issues/375](url)
[https://github.com/bounswe/bounswe2022group1/issues/380](url)
[https://github.com/bounswe/bounswe2022group1/issues/381](url)
[https://github.com/bounswe/bounswe2022group1/issues/382](url)
[https://github.com/bounswe/bounswe2022group1/issues/383](url)
[https://github.com/bounswe/bounswe2022group1/issues/387](url)
[https://github.com/bounswe/bounswe2022group1/issues/389](url)
[https://github.com/bounswe/bounswe2022group1/issues/394](url)

**Tasks to Do:**

- [x] add issue labels
- [x] add related links

*Task Deadline:* 1.11.2022 11:00

*Final Situation:*

**Comment by egetaga** [comment]
All the tasks here are done. Well done! I am closing the issue.
