### ISSUE TITLE
Research topics & Who will do it.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#48]
`Purpose:` Spliting the research topics into team members
`Deadline:` Next meeting.

I went over the project and it seems the following is our research topics.
![image](https://user-images.githubusercontent.com/62199007/158282877-67e41b99-ac4b-46bd-b5fb-c221be41e0f8.png)
Last meeting we decided to assign this to people @omerozdemir1  @egetaga @elxif . However, there are 6 topics. If no one disagrees, we can split the task into 6 people. 

Since we were the first ones (@omerozdemir1  @egetaga @elxif ), we have privilege to choose whatever topic we want. 
I am picking "Semantic Search" topic if it is okay for @egetaga and @elxif .

When @egetaga and @elxif  choose their topic, anyone in the group can assign this task to herself/himself. When the number of assignees is equal to 6, we can close the issue.

**Comment by kadirgokhann** [comment]
I am picking KVKK rules.

**Comment by egetaga** [comment]
We have more than 6 people in the team. For a better understanding of topics, some more advanced topics should be allocated to more than one person. I would like to take **Semantic Search**, together with @omerozdemir1  as well.

**Comment by efekankavalci** [comment]
I agree with @egetaga that more than one person should work on a topic. I would like to contribute to the research of GDPR.

**Comment by harunerkurt** [comment]
I also picked KVKK rules.

**Comment by acyishere** [comment]
Me and @ecesrkn will handle W3C Web Annotation Data Model

**Comment by elxif** [comment]
@gecemavisioa and I will do research on W3C GeoInfo.

**Comment by omerozdemir1** [comment]
Work distribution is done. Therefore, I am closing issue.
