### ISSUE TITLE
Evaluation of tools and processes: Discord, GitHub

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#493]
**Issue Description:** 

I will add a contribution to Ece's [evaluation](https://github.com/bounswe/bounswe2022group1/issues/484) in Discord and GitHub subtitles.

**Tasks to Do:**

- [x] Evaluate Discord
- [x] Evaluate GitHub
- [x] Update the Group Review (Milestone 1) report

*Task Deadline:*  4/11/2022 17:00

*Final situation: done*

**Comment by ecesrkn** [comment]
I already did those evaluations. You can see [Issue #484](https://github.com/bounswe/bounswe2022group1/issues/484)

**Comment by hseyyidkaplan** [comment]
> I already did those evaluations. You can see [Issue #484](https://github.com/bounswe/bounswe2022group1/issues/484)

I will add to your contributions and I am aware what you have done so far.

**Comment by hseyyidkaplan** [comment]
I have done it. Could you @ecesrkn please review and if it is ok, close the issue?

**Comment by hseyyidkaplan** [comment]
Completed!
