### ISSUE TITLE
Group Review (Milestone 1) - Responsibilities and Summary of Individual Work

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#498]
**Issue Description:** 

I will add my responsibilities through Milestone 1 and summary of my individual work.

**Tasks to Do:**

- [x] Add Responsibilities
- [x] Add Summary of Individual Work
- [x] Update the Group Review (Milestone 1) report

*Task Deadline:*  4/11/2022 20:00

*Reviewer:* @kamilkorkut

*Final situation: done*

**Comment by hseyyidkaplan** [comment]
I have just done this task. Could you please review @kamilkorkut and if ok, change the label to 'Status: Completed' and close the issue?

**Comment by kamilkorkut** [comment]
It seems okay. I am closing the issue.
