### ISSUE TITLE
Learning Space Detail Page Design

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#530]
### First Version
- [x] add a title of '{space_name} learning space' 
- [ ] add a section for different content types (at least 5)
- [x] add a contributor sidebar
- [x] add 'join' button and 'add content' dropdown menu features (@kamilkorkut )
- [x] commit the changes of the first version
- [x] put screenshot of page as an issue comment

### Second Version
- [ ] add a background theme
- [ ] add a link to detail page directs to showroom page
- [ ] edit a contributor sidebar such GitHub's one

**Comment by hseyyidkaplan** [comment]
I want to add contributor sidebar similar to GitHub's and I am working on it.

![image](https://user-images.githubusercontent.com/32467338/203277942-a3b67443-9f66-41fb-aea4-0f71feab5353.png)

**Comment by hseyyidkaplan** [comment]
I completed the first version of Detail Page.
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/32467338/203294241-46d0137a-4286-428b-8d37-f20d864b5364.png">

**Comment by kamilkorkut** [comment]
I completed my part.
<img width="1194" alt="Screen Shot 2022-12-06 at 19 57 42" src="https://user-images.githubusercontent.com/73702922/205974814-fe680f37-635d-461b-88a1-0eb8cd0ec328.png">
<img width="1178" alt="Screen Shot 2022-12-06 at 19 58 09" src="https://user-images.githubusercontent.com/73702922/205974835-5039fb9c-c9b6-470d-a734-f15614030388.png">
