### ISSUE TITLE
Backend: Logout Endpoint

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#531]
**Issue Description:**

If I'm not doing something wrong, I couldn't use the logout endpoint. Can you take a look?

<img width="1333" alt="Screen Shot 2022-11-22 at 15 48 51" src="https://user-images.githubusercontent.com/74508086/203318367-45eda60f-b4f1-44f8-b244-9c106d17a88c.png">

<img width="737" alt="Screen Shot 2022-11-22 at 15 49 22" src="https://user-images.githubusercontent.com/74508086/203318399-74a38bea-510b-46c7-95d0-eee38f2751e7.png">
<img width="684" alt="Screen Shot 2022-11-22 at 15 49 27" src="https://user-images.githubusercontent.com/74508086/203318411-cc5d3a28-d7b9-46fb-a3f6-84b34b4d5f0f.png">

**Tasks to Do:**

- [] check whether or not the logout endpoint is working

*Task Deadline:* 25.11.2022 13.00

*CC:*  @mstfatay  @kadirgokhann

**Comment by mstfatay** [comment]
Hi Kadir! It is not a bug. You misused the authorization header. Try this scheme for the header (instead of "token"):
```
{
    "Authorization": "token 8f49b55432ff0d46ec1cc4564910fb356baebe9d5a832b027b138de6b014d2b4"
}
```
This scheme will be used for every API call that requires authentication. 

Let me know if that works.
