### ISSUE TITLE
Backend - Implement Discussion API

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#540]
**Issue Description:** 
We should implement API for discussion. I can't give more information right now, details should be discussed.

**Tasks to Do:**

*Task Deadline:*  

*Final situation:

*Reviewer* 

*Reviewer Deadline*

**Comment by egetaga** [comment]
I have implemented the discussion api as follows https://github.com/bounswe/bounswe2022group1/issues/548.

**Comment by egetaga** [comment]
As discussion is implemented, I am closing the issue.
