### ISSUE TITLE
Profile Page API

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#558]
**Issue Description:** 
We should implement APIs for the user profile page. On the user profile page those pieces of information will be shown:
- username
- email
- profile photo
- learning spaces that the user is enrolled
**Tasks to Do:**
- [x] Implement an endpoint for posting user page
- [x] Implement an endpoint for getting user page information

*Task Deadline:*  03/12/2022 

*Final situation:* Done

**Comment by egetaga** [comment]
Again, both POST and GET are implemented. So, I am closing the issue.
