### ISSUE TITLE
Github Logins on Personal Pages

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#56]
Based on the PS(16.03.2022), everyone should ensure that they added login of their github accounts on personal pages. My login is added my personal page [check](https://github.com/bounswe/bounswe2022group1/wiki/Kadir-Gokhan-Sezer).

After everyone adds the login, this issue will be closed.

**Comment by ecesrkn** [comment]
Also, we are told to add an image to our personal wiki page too (picture of ourselves, or something like an avatar)

**Comment by ecesrkn** [comment]
Done 👍

**Comment by harunerkurt** [comment]
- All team members checked.

- Added GitHub Account name for Ahmet Yazıcı and Osman Fehmi Albayrak.

- Harun sami's own personal wiki page has not yet been created and his GitHub account is not found.
