### ISSUE TITLE
Backend- Unique and Valid Email

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#567]
**Issue Description:**
In order to use the reset password functionality user should register with a valid and unique email. We should update register feature of backend.

**Tasks to Do:**

- [x] fix the emil bug

*Task Deadline:* 
04.12.2022 18:00

*Final Situation:*
I fixed this bug and the pull request can be seen [here](https://github.com/bounswe/bounswe2022group1/pull/566)

*Reviewer:*  
@mstfatay

**Comment by egetaga** [comment]
I've reviewed the changes. It is well-done. I am closing the issue.
