### ISSUE TITLE
Customer Meeting Notes

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#57]
After the PS(16.03.2022) ends, all of the answers should be arranged then added the [page](https://github.com/bounswe/bounswe2022group1/wiki/Consumer-Meeting-Notes).

Deadline: 18.03.2022

**Comment by kadirgokhann** [comment]
The [page](https://github.com/bounswe/bounswe2022group1/wiki/Consumer-Meeting-Notes) is added the navigator.

**Comment by efekankavalci** [comment]
I have documented the first part of the Q&A [here](https://docs.google.com/document/d/1OLVT4v7q9lmquRNkOSsT3qvFm5oMZA3Zs6HYlufVKb0/edit?usp=sharing). After we finish it with @kadirgokhann we can put it into the corresponding page in the navigator.

Also I changed the title to customer meeting notes, which is more correct.

**Comment by kadirgokhann** [comment]
Sorry for delay, the updated version is [here](https://docs.google.com/document/d/1dHCs2KNDFuWvIY_xqJNyfzEFc1L3IN0xPXPDyvWMkLs/edit?usp=sharing).

**Comment by kadirgokhann** [comment]
Added the answers to this [link](https://github.com/bounswe/bounswe2022group1/wiki/Consumer-Meeting-Notes)

**Comment by efekankavalci** [comment]
I reviewed the answers and edited the page to a more readable format. Also the title was mistakenly written as "Consumer meeting notes" again, I changed it too; thus the old link does not work, this is the [new link](https://github.com/bounswe/bounswe2022group1/wiki/Customer-Meeting-%231-Notes). I also replaced the corresponding link with the new one in the sidebar of the wiki page.
