### ISSUE TITLE
Frontend: New Aws Account

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#576]
**Issue Description:**

Since my free aws account time is finished, we need another account to use static IP. In order to handle this issue, @ecesrkn will create an account. Then, we will use that account for deployment.

**Tasks to Do:**

- [x] open AWS account

*Task Deadline:* 05.12.2022 13.00

*Reviewer:*  @ecesrkn

**Comment by ecesrkn** [comment]
I have opened the account, tomorrow we can launch an instance together.
