### ISSUE TITLE
Frontend: Auth Layer of the Project

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#581]
**Issue Description:**

Since our system was not working properly on the Milestone 1, I was the one who took the responsibility to correct that problem.

**Tasks to Do:**

- [x] create an auth layer for the project

*Final Situation:*

-> One cannot go /profile without login.

The page without login.
<img width="1792" alt="Screen Shot 2022-12-04 at 23 51 53" src="https://user-images.githubusercontent.com/74508086/205514921-a3710125-94ff-4ecc-a05d-ce3b097757b9.png">

After clicking the login button.

<img width="1792" alt="Screen Shot 2022-12-04 at 23 52 17" src="https://user-images.githubusercontent.com/74508086/205514936-05d8fcba-2015-4aa7-95d4-41bf73fcf780.png">

One can go /profile now.
<img width="1790" alt="Screen Shot 2022-12-04 at 23 52 34" src="https://user-images.githubusercontent.com/74508086/205514949-3fb6131d-dcdd-4099-a1cb-a3cc3f5e565a.png">

And after clicking the logout button, one cannot go /profile again.
All related possible problems are solved.
<img width="655" alt="Screen Shot 2022-12-04 at 23 53 49" src="https://user-images.githubusercontent.com/74508086/205515007-344ad816-2a8c-474b-b394-5e1dd1944414.png">

*Reviewer:*  @ecesrkn  

*Review Deadline:* 05.12.2022 15.00

**Comment by ecesrkn** [comment]
I reviewed it, thank you for the contribution!
