### ISSUE TITLE
Frontend: Content page

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#589]
Description:
Implement the contents view page and the functionalities related to them.

Tasks:

- [x] Implement ContentPage.js
- [x] Fetch content data from API
- [x] Fetch Discussion from API
- [x] Implement submitting a new discussion content

Final: my work is under the branch frontend-content. The related pull request is here: [#pr558](https://github.com/bounswe/bounswe2022group1/pull/588)

Deadline: 04.12.2022 23.59
Reviewer: @kadirgokhann

**Comment by kadirgokhann** [comment]
I checked the implementation, they all seem fine.
