### ISSUE TITLE
Editing Navigator of  Wiki 

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#6]
The navigator of the wiki should be edited and arranged.

**Comment by mstfatay** [comment]
Created sidebar.

**Comment by kadirgokhann** [comment]
I added icons to Team Members and Meeting Notes.

**Comment by kadirgokhann** [comment]
Changed the titles, aranged the fonts and added the page of Meeting 1.

**Comment by mstfatay** [comment]
Looks pretty good.
