### ISSUE TITLE
Preparing the initial version of the requirements for the Online Learning Platform

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#63]
We should prepare the initial version of the **requirements** for the _Online Learning Platform_ project. We haven't prepared it yet, since we believed it would be better to prepare them after the customer meeting, which was held on 16.03.2022, today. 

- Prepare the list of requirements for the _Online Learning Platform_ project.
- Deadline: 22.03.2022

**Comment by egetaga** [comment]
In our meeting with @ecesrkn and @efekankavalci, we have prepared an initial version of requirements, which need further revisions and contribution. The details should be expanded. In total, our contributions can be summarized as follows:

- We have prepared the general layout of requirements as can be seen [here](https://github.com/bounswe/bounswe2022group1/wiki/Requirements).

- We have added the glossary which was previously written by me on top of the requirements. To see the what I did in preparing glossary, you can check [this issue](https://github.com/bounswe/bounswe2022group1/issues/38).

- I did solely prepare 1.1.1 and 1.1.2 on [here](https://github.com/bounswe/bounswe2022group1/wiki/Requirements).

**Comment by ecesrkn** [comment]
I prepared requirements under categories 1.1.6 and 1.1.7 on a separate page and then merged them to the main Requirements page. (revision number: [4a28fd6](https://github.com/bounswe/bounswe2022group1/wiki/Requirements/4a28fd668292d6cf425c7c98ea686ce74d09e966))

**Comment by egetaga** [comment]
My latest contributions and the reasons for closing the issue are summarized below:
- I prepared **1.2.2** **Pages** requirements in the [requirements wiki](https://github.com/bounswe/bounswe2022group1/wiki/Requirements). 

- Now the initial version of the [requirements](https://github.com/bounswe/bounswe2022group1/wiki/Requirements) is finished.

- Closing the issue since everyone contributed to the issue and our glossary together with requirements are prepared.
