### ISSUE TITLE
Group Review and UI/UX Android , Individual Report for Milestone2

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#643]
`Description:` I will fill the Individual report, Tabular Format for Ömer Özdemir, group review and UI/UX parts for milestone2.
`Deadline:` 8 December 2022 23:59

**Comment by omerozdemir1** [comment]
Done.

**Comment by gecemavisioa** [comment]
We added UI/UX for android milestone 2, can be seen here:
- [Screenshots](https://github.com/bounswe/bounswe2022group1/wiki/UI-UX-Android)
- [Related Codes](https://github.com/bounswe/bounswe2022group1/wiki/UI-UX-Related-codes.)
