### ISSUE TITLE
W3C Standards Research

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#65]
We should make a research on W3C Standards and add it to wiki.

Deadline: 20.03.2022

**Comment by mstfatay** [comment]
Wiki page of the research can be reached using this [link](https://github.com/bounswe/bounswe2022group1/wiki/W3C-Standarts).

**Comment by kamilkorkut** [comment]
I have researched the topic and updated the related wiki page.

**Comment by kamilkorkut** [comment]
I have updated the related wiki page again. I'm closing the issue.
