### ISSUE TITLE
Meeting #3 Notes 17.03.2022

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#67]
To organize the talks at the meeting and upload them to the required [url](https://github.com/bounswe/bounswe2022group1/wiki/Meeting-3) 

Deadline: 23:59-17.03.2022

**Comment by kadirgokhann** [comment]
Created the url and added to the navigator.

**Comment by ecesrkn** [comment]
Didn't see the url you have added.
I created this [page](https://github.com/bounswe/bounswe2022group1/wiki/Meeting-Notes-%233-(16.03.2022)) which contains weekly meeting notes #3 
I added it to the navigator and the main page.

Even if it is not on the navigator under meeting #3 now, I think we should keep [your notes](https://github.com/bounswe/bounswe2022group1/wiki/Meeting-3) as well.(I don't know where)

**Comment by kadirgokhann** [comment]
I appended the my draft to your notes, is it okay? Or should we keep my notes in another url?

**Comment by ecesrkn** [comment]
I think it looks good and organized. I removed the "responsibilities" part since they are mentioned in action items. I think we can close this issue now. @kadirgokhann
