### ISSUE TITLE
New Button design and some configuration changes.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#690]
**Issue Description:**

- I introduced a new button design
- I changed the some of the configuration files for material design.
- All buttons available in the Android app are updated with the new button design.
- PrimaryColors1,2,3,4 is added. Only these primary colors will be used from now on.

**Photos:**
![image](https://user-images.githubusercontent.com/62199007/207743703-81ca60e4-de29-4f64-9321-3cd4bb2319fa.png)
![image](https://user-images.githubusercontent.com/62199007/207743740-1bedd3e3-ee2d-4f3a-ae09-baadec70ffd5.png)

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
17.12.2022

**Comment by gecemavisioa** [comment]
Primary colors match with our website. New button design looks cool!
