### ISSUE TITLE
Design improvement for Android

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#692]
**Issue Description:**

- I designed a new background, which we will use it from now on.
- I picked a new font (walter_turncoat), which we will use it for all texts from now on.
- I changed all backgrounds in Android app with the new one.
- I changed all fonts in the Android app with the new one.
- Some of the design photos are given below for just illustration purposes.
- Text sizes should be always 20dp.
- For input texts we will use @font/andika.

**Photos**
![image](https://user-images.githubusercontent.com/62199007/208028657-0eeaeb0f-608c-421a-801d-d5373fab841b.png)
![image](https://user-images.githubusercontent.com/62199007/207772630-b6458eea-c243-42b0-8181-dc76648f2f56.png)
![image](https://user-images.githubusercontent.com/62199007/207775384-8b4882e7-8445-4cea-b717-aee4ab89bf79.png)
![image](https://user-images.githubusercontent.com/62199007/207772663-4e943913-d1d7-4fff-8dc0-ab758a5992a2.png)
![image](https://user-images.githubusercontent.com/62199007/207776775-83458dfe-3135-4bf3-9538-a13169883de5.png)
![image](https://user-images.githubusercontent.com/62199007/207778997-00657d35-0ea9-461e-be14-25bd7a78ae58.png)
![image](https://user-images.githubusercontent.com/62199007/207776357-25f98e86-d7b2-45ae-af29-04a4e9bd9189.png)

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
16.12.2022

**Comment by gecemavisioa** [comment]
It's a good idea to determine font size for assuring coherence. Also, your font choices look great! We can make some improvements on background.
