### ISSUE TITLE
Learning Space Menu is created.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#694]
**Issue Description:**
For better UI/UX experience, I created a menu page (the following).
![image](https://user-images.githubusercontent.com/62199007/208024002-d742b2f0-f5f1-4685-bd57-a623719f5a1f.png)

*Final Situation:*
Completed.

*Reviewer:*  
@gecemavisioa 
*Review Deadline:*
16.12.2022

**Comment by gecemavisioa** [comment]
Looks cool.
