### ISSUE TITLE
Learning Space Resource and Members new design.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#695]
**Issue Description:**
LearningSpace2 was too compact. Therefore, I splitted the page into multiple pages.

**Photos:**
![image](https://user-images.githubusercontent.com/62199007/208024260-b9529415-3952-447e-b5c9-249b57ce64a1.png)
![image](https://user-images.githubusercontent.com/62199007/208024270-a9589224-d3ce-4f14-a640-71bb2fdd1698.png)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
17.12.2022

**Comment by gecemavisioa** [comment]
Good idea splittin these two pages, list view also looks good!
