### ISSUE TITLE
Taking notes functionality is needed.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#699]
**Issue Description:**
For the following page (resource itself), the user should be able to take notes.

- I need one get method to retrieve the note .
- I need one post method to save note.

![image](https://user-images.githubusercontent.com/62199007/208028327-34f096d7-eb41-4f65-b498-4af15d8dde7e.png)

**Tasks to Do:**

- [ ] User should be able to take notes.

*Task Deadline:* 
20.12.2022

*Final Situation:*
In progress.

*Reviewer:*  
@egetaga 
@kkadirkkalkan 

*Review Deadline:*
20.12.2022

**Comment by kkadirkkalkan** [comment]
I am working on this new feature.

**Comment by kkadirkkalkan** [comment]
I implemented this functionality. Takin note functionality can be seen via this [pull request](https://github.com/bounswe/bounswe2022group1/pull/743)

**Comment by omerozdemir1** [comment]
Thanks!
