### ISSUE TITLE
Android: UI Improvements

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#702]
* There were border radius in the background and linear gradient. To improve and simplify the look, I removed them.
* Updated button designs according to the new background.
* Adapted text colors to the background
![image](https://user-images.githubusercontent.com/73769340/208125728-869cff68-c7c6-4ef1-81cc-2418d06ec3fb.png)

These changes are applied to the following pages too.

Reviewer:
@omerozdemir1 

Review Deadline:
17.12.2022

**Comment by omerozdemir1** [comment]
Seems good. Thanks!
