### ISSUE TITLE
Sign-in and Sign-up design changes are made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#706]
**Issue Description:**
I changed sign-in and sign-up pages for better UI/UX experience. The following illustrates the new design.

**Photos:**
![image](https://user-images.githubusercontent.com/62199007/208146737-ae384a54-7cfd-46ac-92d8-0efc0e9937fc.png)
![image](https://user-images.githubusercontent.com/62199007/208146754-63fe5330-f925-4941-a7fc-cfcfeeda9873.png)

*Final Situation:*
Completed.

*Reviewer:* 
@gecemavisioa 
@acyishere  

*Review Deadline:*
17.12.2022

**Comment by gecemavisioa** [comment]
Looks more simple and elegant, thank you!
