### ISSUE TITLE
Android: Profile Edit Page

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#709]
I designed a page for profile editing where user can add to their profile :
* A profile photo
* An about me section

![image](https://user-images.githubusercontent.com/73769340/208156681-769b8b74-d34a-4208-82d0-1c14cf8980f8.png)

Users are able to select a picture from their gallery, and upload it:

![image](https://user-images.githubusercontent.com/73769340/208156884-08065cce-f12f-4c00-acd9-95a5e182830a.png)

By clicking the "x" icon they can delete their upload:

![image](https://user-images.githubusercontent.com/73769340/208157196-09e4fb26-8bb7-4b5d-a769-ffc528e79f2f.png)

The related endpoint was waiting an image file as request body, it should be converted to a string field (Base64).
Then, back-end connection will be implemented.

*Reviewer:*  @omerozdemir1 

*Review Deadline:* 17.12.2022

**Comment by omerozdemir1** [comment]
It awesome. Thanks!
