### ISSUE TITLE
Profile page enrolled learning spaces is seen.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#713]
**Issue Description:**
I updated the profile page so that It shows enrolled learning spaces of the user. When the user selects an item, it lands on the related learning space.

**Photos:**
![image](https://user-images.githubusercontent.com/62199007/208180026-70298fd4-bf2f-416a-84f1-c418b2c924d2.png)
![image](https://user-images.githubusercontent.com/62199007/208180075-7d1e83ab-1b65-4a37-911b-ed8a72bb0ea7.png)
`When I click on the gitar I land in the gitar learning space`
![image](https://user-images.githubusercontent.com/62199007/208180194-1eacc59b-7fb3-45ad-8d4a-4d8239e8b91e.png)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
17.12.2022

**Comment by gecemavisioa** [comment]
Nice functionality, thank you!
