### ISSUE TITLE
Resource page new design is introduced.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#716]
**Issue Description:**
I resigned the resource page (the following). Necessary back-end connections will be made later.

**Photos:**
![image](https://user-images.githubusercontent.com/62199007/208214391-6cd5fad7-4b87-47f0-8436-e156575403c2.png)
![image](https://user-images.githubusercontent.com/62199007/208214396-ee85a4a4-ee8d-4eb6-9390-64159ba36f42.png)

`When I click on up vote button`
![image](https://user-images.githubusercontent.com/62199007/208214403-b9135e33-39a1-48f7-9616-01786ceb7259.png)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
20.12.2022

**Comment by gecemavisioa** [comment]
Resource itself takes all the attention now. Bottom menu is a great idea! Once we complete implementing annotations, a button can be added to the bottom menu for it.
