### ISSUE TITLE
Changing Theme and Logo

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#719]
**Issue Description:**
We used to have a blue-colored theme. However, Android and frontend teams weren't even synced about the actual color of that blue. We decided to change the theme and logo totally.
I want to find some warm colors to show our platform as a sincere and collaborative learning environment. I will create a new logo according to the new color palette respecting the sincere environment aspect again.

**Tasks to Do:**

- [x] Find a new color palette
- [x] Create a new logo

*Task Deadline:* 
17.12.2022 20:00

*Final Situation:*
Here is our new color palette:
![WhatsApp Image 2022-12-13 at 17 47 21](https://user-images.githubusercontent.com/46002371/208239082-8232d0f4-ec62-4e14-b958-db75fd868862.jpeg)
As can be seen, I selected warm colors.

I created a logo too with the given color palette.
![budemi logo](https://user-images.githubusercontent.com/46002371/208239111-ffe2a45f-1d64-4274-85d6-1b5e3f71f164.png)

*Reviewer:*  
@omerozdemir1 

*Review Deadline:*
19.12.2022 20:00

**Comment by omerozdemir1** [comment]
We will switch to rubik font. Which one do you suggest?
![image](https://user-images.githubusercontent.com/62199007/208248372-355d70f4-c03e-4980-80f1-f8a775e30126.png)

**Comment by mstfatay** [comment]
I suppose regular or medium should work well. Headers might be a bolter one. We should almost never use an italic font.

**Comment by omerozdemir1** [comment]
Thanks! I changed the fonts accordingly.
