### ISSUE TITLE
Creating Scenario and Mockups for Teacher Role

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#72]
The following should be defined.

- The user and his/her persona
- Preconditions
- Specific actions to achieve some desired goal
- Acceptance criteria

Mockups should be created for the Teacher role from end to end according to the following rules.

- Mockups must present concrete examples
- Use canva for creating mockups
- The mockups do not focus on user interface slickness.
- All material must be shared on repo.

**Comment by harunerkurt** [comment]
Home page for student user is created on [canva](https://www.canva.com/design/DAE7O8w_cVM/U37gLg8cyUxIwRm1JPK_jQ/).

**Comment by harunerkurt** [comment]
[Teacher User Web Scenario and Mockup](https://github.com/bounswe/bounswe2022group1/wiki/Teacher-User-Web-Scenario-and-Mockup) page is created.

- Persona, Story, Preconditions, Goals, Scenario section about teacher user is added.

**Comment by efekankavalci** [comment]
As you know, we did not complete the acceptance criteria in the scenario in our subgroup meeting. We need to finish it in addition to the mock-ups. I will be working on these this evening.

**Comment by efekankavalci** [comment]
I have added some acceptance criteria to the [document](https://docs.google.com/document/d/1G6g3dEQu7_VxdGm1TPYCE4NbQLqq4qt1iCPRm9Yv2HI/edit?userstoinvite=erkurtharun@gmail.com&actionButton=1), we should review them and add new ones. I also tried some stuff for the mock-ups but I think we should talk about them together.

**Comment by harunerkurt** [comment]
I uploaded the mockups I created to the [wiki page](https://github.com/bounswe/bounswe2022group1/wiki/Teacher-User-Web-Scenario-and-Mockup).

- [Login Page](https://user-images.githubusercontent.com/49256548/159708768-c0c90c65-b065-4921-885b-21dcfee0147f.png)
- [Home Page](https://user-images.githubusercontent.com/49256548/159708834-7ed69147-dd6e-4550-8e97-6b60ec1826aa.png)
- [Dashboard for account](https://user-images.githubusercontent.com/49256548/159708907-cba3364f-152b-4efc-a54c-075276c795d1.png)
- [My Courses overview](https://user-images.githubusercontent.com/49256548/159708962-90855e5d-86b6-4d7e-9b21-345a81b07491.png)

**Comment by harunerkurt** [comment]
I added [the home page](https://user-images.githubusercontent.com/49256548/159714968-bdc74865-9544-4e6a-8f71-9e073acb594c.png) I created for users who are not logged in.
I also edited the scenario part

**Comment by harunerkurt** [comment]
I updated preconditions according to the scenario

**Comment by kamilkorkut** [comment]
I updated opening course pages in Canva.

**Comment by efekankavalci** [comment]
I have added 3 acceptance criteria from [requirements](https://github.com/bounswe/bounswe2022group1/wiki/Requirements).

**Comment by egetaga** [comment]
Corrected the English usage in all parts of the mock-up and the scenario. My fixes are [here](https://github.com/bounswe/bounswe2022group1/wiki/Teacher-User-Web-Scenario-and-Mockup) and they include: 

- correcting typos,

- converting ambiguous sentences to their intended versions

- correcting article usages

**Comment by harunerkurt** [comment]
I updated goals according to the scenario.

**Comment by efekankavalci** [comment]
I have added cursors to the mockups and reviewed the [page](https://github.com/bounswe/bounswe2022group1/wiki/Teacher-User-Web-Scenario-and-Mockup).
