### ISSUE TITLE
Resource (Notes,Discussion,Resource,Edit) functionality is done

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#721]
**Issue Description:**
Back-end connection is made for discussion. Since there is no end-point for edit, votes and notes, their infrastructure is ready.

**Photos**
When I click on notes:
![image](https://user-images.githubusercontent.com/62199007/208248753-bda5d8c9-6c2a-4d72-8b81-6b12afc85db6.png)
![image](https://user-images.githubusercontent.com/62199007/208248755-90e4f0e2-64a3-47d0-80c2-9333f914eb39.png)

When I click on discussion:
![image](https://user-images.githubusercontent.com/62199007/208248765-715e6b72-2a2e-433a-84a4-2201e66e4b01.png)
![image](https://user-images.githubusercontent.com/62199007/208248770-5e0ed73e-1c63-4347-adab-6b398ab27174.png)

When I click on edit, the textview becomes editable.
![image](https://user-images.githubusercontent.com/62199007/208248829-0a0e2f4c-3d77-4426-a629-96c40ca84cf3.png)

*Final Situation:*
Completed.

*Reviewer:*
@gecemavisioa 
@acyishere   

*Review Deadline:*
18.12.2022

**Comment by gecemavisioa** [comment]
Splitting these pages is a good idea, pages looks nice!
