### ISSUE TITLE
Frontend: Creating Learning Space

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#728]
**Issue Description:**

Now, as can be seen below, we can create a learning space via more convenient way. 

**Tasks to Do:**

- [x] change the type of the creating new learning space

*Task Deadline:* 

*Final Situation:*
<img width="1792" alt="Screen Shot 2022-12-18 at 17 39 28" src="https://user-images.githubusercontent.com/74508086/208304476-fd15d2fb-2ad3-40a3-a30a-6088e7ac26b4.png">

*Reviewer:*  @kamilkorkut 

*Review Deadline:* 22.12.2022

**Comment by kamilkorkut** [comment]
This design is much better. Good work!
