### ISSUE TITLE
Backend: Photo of a Learning Space

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#729]
**Issue Description:**

On the issues #727 #728, we can see the new version of the homepage.  We need a backend implementation of the photos of the learning spaces.

**Tasks to Do:**

- [x] create an endpoint to upload the photos
- [x] create an endpoint to get the photos

*Task Deadline:* 20.12.2022

*Reviewer:*  @kadirgokhann 

*Review Deadline:* 20.12.2022

**Comment by kkadirkkalkan** [comment]
I updated learning space POST and GET endpoints. A user can add an image while creating a learning space. Changes can be seen [here](https://github.com/bounswe/bounswe2022group1/pull/741)

**Comment by kadirgokhann** [comment]
Thank you.
