### ISSUE TITLE
Creating Scenario and Mockups for Guest Role

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#73]
`Purpose:` The following should be defined.

The user and his/her persona
Preconditions
Specific actions to achieve some desired goal
Acceptance criteria
Mockups should be created for the Guest role from end to end according to the following rules.

Mockups must present concrete examples
Use canva for creating mockups
The mockups do not focus on user interface slickness.
All material must be shared on repo.

`Deadline` 23.03.2022

**Comment by harunerkurt** [comment]
Homepage for guest user is created.

**Comment by egetaga** [comment]
I reviewed your work. Acceptance criteria, preconditions and goals should be numbered. Other than that, it seems pretty fine.

**Comment by mstfatay** [comment]
I met Ömer Özdemir. We updated scenario and created mockup images using templates done by other group members.

**Comment by omerozdemir1** [comment]
I review the page and it is fine. The task is done. Therefore, I am closing the issue.
