### ISSUE TITLE
New Learning Space List Page Design

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#731]
Since we are gonna display more information about learning spaces, I have updated the page. 
Now, users are able to see not only learning space name, but also its description, owner and creation time.
For displaying more information, waiting for endpoint update from backend.
Description and created at displays are dummy texts for now.
![image](https://user-images.githubusercontent.com/73769340/208305493-286725aa-222d-4908-bcd9-0d842e142c2d.png)

*Final Situation:*
Completed.

*Reviewer:*
@omerozdemir1 
@acyishere   

*Review Deadline:*
20.12.2022

**Comment by omerozdemir1** [comment]
Seems better UI/UX than before. Thanks for your effort.
