### ISSUE TITLE
Android: Navigation Bar Improvements

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#734]
* Our logo added to the navigation bar.
* Navigation bar width is decreased.
* Going to profile page and sign out functions added.
![image](https://user-images.githubusercontent.com/73769340/208308666-e88a3d69-83f4-42a0-aba7-bfe90e25747b.png)

*Final Situation:*
Completed.
*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
20.12.2022

**Comment by omerozdemir1** [comment]
It is working and seems good. I think still more improvement can be achieved.
