### ISSUE TITLE
Resource page bottom bar becomes shorter and save functionality is added.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#736]
**Issue Description:**

- Clicking on notes,edit or discussion makes bottom bar shorter. Previously, user had to make it shorter.
- Clicking on edit button, will result in the following bottom bar. (i.e. save button is added)
![image](https://user-images.githubusercontent.com/62199007/208313490-261bf0e6-0aff-41ea-8905-61569ca1fc1c.png)

*Final Situation:*
Completed.

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
20.12.2022

**Comment by gecemavisioa** [comment]
Nice feature, improves UX greatly. Thanks!
