### ISSUE TITLE
Resource listing owner and votes is shown.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#738]
**Issue Description:**
Owner and number of votes of the content is shown in the resource listing page.
![image](https://user-images.githubusercontent.com/62199007/208322774-25eab722-cc38-46ba-a7e4-518878718de3.png)

*Final Situation:*
Completed.

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
21.12.2022

**Comment by gecemavisioa** [comment]
Nice and simple design. Works properly, thanks!
