### ISSUE TITLE
Add/Remove favorite is added.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#739]
**Issue Description:**
Add favorite icon in the following page is changed. Also, When user clicks on add favorite, icon and text are changed to remove favorite.
![image](https://user-images.githubusercontent.com/62199007/208485881-dcf62cb0-ee62-4a12-bd81-9316c03b34c9.png)
![image](https://user-images.githubusercontent.com/62199007/208485990-38cf49d8-0de0-4d1b-9576-f24399410032.png)

*Final Situation:*
Completed.

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
20.12.2022

**Comment by gecemavisioa** [comment]
Icon looks coherent to the page, good choice, thanks!
