### ISSUE TITLE
Welcome to budemi text in homepage is made sliding

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#740]
**Issue Description:**
Welcome to budemi text in homepage is made sliding.
![image](https://user-images.githubusercontent.com/62199007/208538797-267ec877-cb8b-4e1d-9605-d4163f247a9e.png)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
20.12.2022

**Comment by gecemavisioa** [comment]
This component may be used somewhere, thanks.
