### ISSUE TITLE
Takin Notes Feature

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#744]
**Issue Description:**
Taking note feature should be implemented. Mobile team requested this enhancement. Related issue is [this](https://github.com/bounswe/bounswe2022group1/issues/699) 

**Tasks to Do:**

- [x] implement taking notes feature

*Task Deadline:* 
20.12.2022- 17.00

*Final Situation:*

I have implemented this new feature and added related endpoint. Pull request can be seen [here](https://github.com/bounswe/bounswe2022group1/pull/743)

*Reviewer:*  
@egetaga 

*Review Deadline:*
20.12.2022- 17.00

**Comment by egetaga** [comment]
I controlled your implementation. Everything works fine. I am closing the issue.
