### ISSUE TITLE
UI/UX improvement on resource page.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#745]
**Issue Description:**
For better readability, I added bar between the user texts. See the following.
![image](https://user-images.githubusercontent.com/62199007/208802106-33bd129a-0e9e-4f60-9f66-5f0da237c352.png)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Page design looks cool. Thanks for the update!
