### ISSUE TITLE
Bug fix for profile page

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#747]
**Issue Description:**
I realized that If the user goes to learning spaces that he/she enrolled, members of the learning space is not updated.
[Related commit](https://github.com/bounswe/bounswe2022group1/commit/d78540545904113f90e847f1564fbd28ec3320c4)

*Final Situation:*
Completed.

*Reviewer:*
@gecemavisioa 
@acyishere   

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Seems working thanks!
