### ISSUE TITLE
Markdown is supported in resource page.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#752]
**Issue Description:**
I added markdown and html support for resource page.
Here is an example:
![image](https://user-images.githubusercontent.com/62199007/209244692-c2f2dd75-a54e-44e6-b902-801c92c6d920.png)

*Final Situation:*
Completed

*Reviewer:*
@gecemavisioa 
@acyishere   

*Review Deadline:*
24.12.2022

**Comment by gecemavisioa** [comment]
It is not determined which display type will be used here, but implementing one of them is really helpful! Thanks!
