### ISSUE TITLE
Profile page image back-end connection is made.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#755]
**Issue Description:**
For user:quanex1, image is given by the address:http://3.89.218.253:8000/media/uploads/Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2022-09-28_052625.png
![image](https://user-images.githubusercontent.com/62199007/209399222-7c6f7a23-c6ae-483a-b268-d417a1a4d159.png)

and it is shown in the android as well.
![image](https://user-images.githubusercontent.com/62199007/209399284-725efbad-2cce-4f3b-aca8-ad2028f9358d.png)

*Final Situation:*
Completed.

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
23.12.2022

**Comment by egetaga** [comment]
Very well done, glad that you made a connection with the backend pretty nicely.

**Comment by gecemavisioa** [comment]
Uploaded photos can be displayed now, but we have still issues about uploading them.
Updates can be followed by [here](https://github.com/bounswe/bounswe2022group1/issues/711)
