### ISSUE TITLE
Add favorite back-end connection is made.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#762]
**Issue Description:**
I have done back-end connection for add favorite functionality in learning space.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/f630bcc58b59faa024e921ed0fdbbd967f47cc30)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Seems working, thanks for the implementation
