### ISSUE TITLE
Remove favorite back-end connection is made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#763]
**Issue Description:**
I have done back-end connection for remove favorite functionality in learning space.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/0ee9df073a1e6d1bfdba64ac2120388f155b1641)

*Final Situation:*
Completed

*Reviewer:*  
@gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Seems working. Thanks!
