### ISSUE TITLE
Android: Search Bar Moved to the Home Page

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#767]
**Issue Description:**

Home page needs to be redesigned. We decided to add search bar to the top of the home page.

* Added Search View on the top of the page.
* Upon clicking it user directed to the search page.

![image](https://user-images.githubusercontent.com/73769340/209434866-6022175f-d2c0-4d52-96ba-1fa3d4893687.png)

If you click the search view, you are directed to the search page:
![image](https://user-images.githubusercontent.com/73769340/209434904-37d4ae7c-5d75-4b1f-872d-21b326198e98.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
I liked the design, thanks!
