### ISSUE TITLE
Favorite learning spaces added to the home page

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#772]
Favorite learning spaces section added to the home page.
API connections will be implemented.
Page design looks like this:
![image](https://user-images.githubusercontent.com/73769340/209442656-a1b87806-f489-4da1-b5eb-665f4a77e8ef.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Seems really good. Thanks brother.
