### ISSUE TITLE
Search View related Bug

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#773]
**Issue Description:**
User is directed to the search page by clicking to the search box on the home page.
If users want to go back while they are on the search page, they couldn't do this because of a bug.
This bug is fixed.

*Reviewer:*  
@omerozdemir1 

*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
The problem seems to be solved. Thanks!
