### ISSUE TITLE
Android: Learning Space: More information displayed

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#774]
**Issue Description:**

I asked for description, created at and owner field additions to the learning space fields in this [issue](https://github.com/bounswe/bounswe2022group1/issues/712). 
After the endpoint updates, I connected new fields to the list.
Also, updated Learning Space Create function by adding a description input field.

![image](https://user-images.githubusercontent.com/73769340/209443140-59dab525-645e-42ca-846a-5e1534fab97f.png)
![image](https://user-images.githubusercontent.com/73769340/209443435-0def2679-04a0-460a-b3e9-2ca9465aa1b1.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Seems really good. Thanks!
