### ISSUE TITLE
Api connection for getting all notes in resource is made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#777]
**Issue Description:**
GET /app/note/ (for getting all notes) is connected to the Android app.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/4e05f5726e0cd0d370a63392de560190217ec272)

*Final Situation:*
Completed.

*Reviewer:*
  @gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
It's working, thanks for the implementation!
