### ISSUE TITLE
Favorite learning Spaces connection completed

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#778]
**Issue Description:**

I listed favorite learning spaces of a user on the home page.
By clicking it, user directed to the related learning space page.
![image](https://user-images.githubusercontent.com/73769340/209446642-6359ba73-53c1-4d4b-a887-c00f008a83bf.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Thanks for paving the way for better UX.
