### ISSUE TITLE
Adding Non-functional Requirements

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#78]
The non functional programming requirements section on this [page](https://github.com/bounswe/bounswe2022group1/wiki/Requirements) should be created

Deadline: 23:59 23.03.2022

**Comment by egetaga** [comment]
Requirements are already created. They should be edited and added. So I changed the title as "Adding Non-functional requirements".

**Comment by harunerkurt** [comment]
I added 3 parts to non-fuctional requirements

- 2.1 Privacy

- 2.2 Security

- 2.3 Accessability

**Comment by kadirgokhann** [comment]
2.4 and 2.5 are added.
