### ISSUE TITLE
Editting note back-end connection is made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#781]
**Issue Description:**
PATCH /app/note/ (for editting a specific note) is connected to the Android app.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/1c9b4ba124476eff2b2340e59b2a2f0969a42fa2)

*Final Situation:*
Completed.

*Reviewer:*
  @gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Works on my device, thanks for the implementation!
