### ISSUE TITLE
Creating a note back-end connection is made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#782]
**Issue Description:**
POST /app/note/ (for creating a specific note) is connected to the Android app.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/59e77fa677c81aa42feb4f59a3a4dbc0c9c4815b)

*Final Situation:*
Completed.

*Reviewer:*
  @gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Works on my local, thanks!
