### ISSUE TITLE
Content edit back-end connection is made

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#783]
**Issue Description:**
PATCH /app/content/ (for editting the content) is connected to the Android app.
[See related commit](https://github.com/bounswe/bounswe2022group1/commit/170202d788553894f797a6b99cb656759d4dcc4a)

*Final Situation:*
Completed.

*Reviewer:*
  @gecemavisioa 

*Review Deadline:*
25.12.2022

**Comment by gecemavisioa** [comment]
Tried on my local, works well. Thank you!
