### ISSUE TITLE
Frontend - updating favicon

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#784]
**Issue Description:**
I will create a new favicon according to our logo. I will add it to our website.

**Tasks to Do:**

- [x] create a new favicon
- [x] add it to website

*Task Deadline:* 
27.12.2022 20:00

*Final Situation:*
The favicon I created:
![favicon](https://user-images.githubusercontent.com/46002371/209451756-07f0e013-7a17-4666-8213-13177990581e.png)

I added it to our website too: https://github.com/bounswe/bounswe2022group1/commit/317edefdf6b675a0bc0fe7993c267b05a71616a1

*Reviewer:*  

*Review Deadline:*
29.12.2022

**Comment by omerozdemir1** [comment]
I liked the favicon. We used it in Android, thanks!
