### ISSUE TITLE
Chating with Suzan Uskudarli on Slack

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#786]
**Issue Description:**
<img width="1512" alt="Screenshot 2022-12-25 at 01 41 35" src="https://user-images.githubusercontent.com/62199007/209452584-79d1f8e5-2c47-4473-8463-5c64c24833a6.png">
<img width="1512" alt="Screenshot 2022-12-25 at 01 41 41" src="https://user-images.githubusercontent.com/62199007/209452587-eda5c9d0-8c73-4a2e-8fe3-08795e74d442.png">
<img width="1512" alt="Screenshot 2022-12-25 at 01 41 48" src="https://user-images.githubusercontent.com/62199007/209452590-75a7a573-1e64-49e5-90a4-11be5a0efb78.png">

**Comment by alper111** [comment]
What does this have to do with the project :D

**Comment by omerozdemir1** [comment]
Sorry for inconvenience

**Comment by uskudarli** [comment]
My sentiments exactly @Alper Ahmetoglu ***@***.***>

**Comment by uskudarli** [comment]
Besides the fact that it is against data sharing policies.
