### ISSUE TITLE
Creating searching part of system requirements

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#79]
I will create [Glossary & Requirements page](https://github.com/bounswe/bounswe2022group1/wiki/Requirements)'s System Requirements part's Searching part.

Deadline: 23:59 23.03.2022

**Comment by mstfatay** [comment]
I finished it with the help of @egetaga .

**Comment by mstfatay** [comment]
Review needed.

**Comment by egetaga** [comment]
- I have fixed some sentences to prevent possible ambiguity.

-  It seems pretty fine. 

- Review is done and I am closing the issue.
