### ISSUE TITLE
Android: Resources of Fav. Learning Spaces

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#793]
**Issue Description:**

In order to increase user experience, favorite learning spaces are already listed on the home page.
We thought that accessing their resources quickly, may increase UX too.
Therefore, resources of favorite Learning Spaces are listed on the home page now.
As swipeView changes its position, resource list is updated according to the displayed learning space on it.

![image](https://user-images.githubusercontent.com/73769340/209474553-4a1ded6c-893e-4416-82db-f38bb7ead46c.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
You are the best. Seems really nice. Thanks!
