### ISSUE TITLE
Android: Navigation Bar Accessible from All Pages

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#795]
**Issue Description:**

Navigation bar was only accessible through the home page. This situation was making hard to rotate between pages.
Therefore, I made navigation bar accessible through all pages.

![image](https://user-images.githubusercontent.com/73769340/209475728-c35be676-801b-4b03-ae94-c9df0b2d467f.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
You are the best teammate ever. Thanks for your effort!
