### ISSUE TITLE
Android: Home Page Resource Owner Bug

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#799]
**Issue Description:**

These owner fields couldn't be read before going to the related learning space.
Since these variables set globally before entering the related spaces, I set them on the home page and the bug is fixed.
![image](https://user-images.githubusercontent.com/73769340/209478288-49e1fc29-42d1-4be6-a520-98a1d348dc6e.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Thanks for the correction.
