### ISSUE TITLE
Android: Resource Notes Bug Fixed

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#806]
**Issue Description:**

Notes of the resource page couldn't be retrieved from the backend since api parameters does not match.
Updated fields to the fields seen below, GET request works:
![image](https://user-images.githubusercontent.com/73769340/209483222-f634c6c1-a72c-4cd5-a268-a948cca12062.png)
We can now receive notes from the backend:
![image](https://user-images.githubusercontent.com/73769340/209483238-028378cf-9b9c-460a-a455-00f5e10c107a.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Thanks for the correction.
