### ISSUE TITLE
Editing Note Functionality implemented

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#807]
**Issue Description:**

Users are now able to update their notes by clicking the edit button and saving.
![image](https://user-images.githubusercontent.com/73769340/209483263-37ebfd85-2514-4157-ba03-7dae87d0df3a.png)
![image](https://user-images.githubusercontent.com/73769340/209483276-96d3ddf5-a83f-4405-b1ec-a7431ad8c739.png)
![image](https://user-images.githubusercontent.com/73769340/209483279-e7af80b5-76d6-437e-b002-7012971a859a.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Thanks for the help.
