### ISSUE TITLE
Implementation of upvote/downvote in resource page

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#810]
**Issue Description:**
I implemented the upvote/downvote functionality in resource page for android app.
[Related PR](https://github.com/bounswe/bounswe2022group1/pull/809)

*Final Situation:*
Completed

*Reviewer:*
@gecemavisioa   

*Review Deadline:*
26.12.2022

**Comment by gecemavisioa** [comment]
Seem working, thanks!
