### ISSUE TITLE
Correcting English usages in the wiki pages

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#82]
Clear and non-ambiguous sentences with nice grammar is vital for expressing ourselves as a team and communicating with the customer. Our wiki pages include grammar mistakes and ambiguous sentences, which may result in a failed communication. Therefore,

- I shall correct typos and English usages in the wiki pages of the navigator, excluding personal pages

- The aim is to facilitate clear and non-ambiguous communication

**Comment by kadirgokhann** [comment]
You touched on a good topic. I also want to be corrected. My idea is that someone has to be in that role throughout the course since this  is another workload.

**Comment by egetaga** [comment]
I am closing this issue, since due to my business I couldn't spend enough time on fixing this minor issue. I will open the issue in my next available time.
