### ISSUE TITLE
Frontend: For Deployment 

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#830]
**Issue Description:**

I can't review right now as we all work in different branches. Can anyone get a build on the branch they are working on? The deployment will be easier for me if she/he fixes his mistakes until I get it.

**Tasks to Do:**

- [ ] build the project

*Task Deadline:*  26.12.2022

*Reviewer:*  @kadirgokhann 

*Review Deadline:* 26.12.2022

**Comment by hseyyidkaplan** [comment]
It is good to build latest version of our app which is up-to-date in `frontend` branch. Could you help to build app according to this branch? Thanks in advance 💮
