### ISSUE TITLE
Backend - Favorites bug

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#836]
**Issue Description:**

@omerozdemir1  from the android team informed us that in our current form, a user may favorite the same learning space multiple times. This is not an expected behavior and shouldn't be observed in the production. So, we should fix it asap. 

**Tasks to Do:**

- [x] Fix the bug related to favoriting a same learning space multiple times

*Task Deadline:* 26.12.2022

*Final Situation:* Done

*Reviewer:*  @kkadirkkalkan

**Comment by egetaga** [comment]
I have fixed the bug and committed the changes in a new PR.

**Comment by kkadirkkalkan** [comment]
Nice work. Since nothing left about this issue I am closing it.
