### ISSUE TITLE
Profile Page is Implemented

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#841]
**Issue Description:**

I was waiting for profile endpoint updates ([Issue #711](https://github.com/bounswe/bounswe2022group1/issues/711)) for implementing the user profile page.
Endpoint update is made and I implemented the page as following:
* If a newly registered user tries to his/her profile, they are redirected to the profile create page.
* After they create their profile, they are returned to the profile page
* Their information is displayed there
* Profile edit feature is disbanded, they can create their profile for once

Profile create page:
![image](https://user-images.githubusercontent.com/73769340/209556168-99f480e0-bf2d-4fa5-a5e4-90fc70e70553.png)

Profile page: 
![image](https://user-images.githubusercontent.com/73769340/209556345-31e868dc-aa36-40dd-a93f-94c693b2f3a6.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
Thanks! It really works.
