### ISSUE TITLE
Home Page Favorite Learning Spaces

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#847]
**Issue Description:**

When there was no learning spaces or resources, home page was looking empty.
In order to solve this problem, I added:
* An empty learning space card which displayed there are no favorite learning spaces
* An empty resource text which displayed there are no resources belongs to the favorite learning space

New design looks like:
![image](https://user-images.githubusercontent.com/73769340/209563775-3768ad0a-fa2a-4c73-bc0e-47a83c38cd4a.png)

*Reviewer:*  
@omerozdemir1 
*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
It is really nice. Thanks!
