### ISSUE TITLE
Unit Tests for New Features

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#850]
**Issue Description:** 
Unit tests for new APIs should be written. I have implemented note and user from username endpoints. I have to write unit tests for these endpoints

**Tasks to Do:**
- [x] write unit tests for note endpoint
- [x] write unit tests for user from username endpoint

*Task Deadline:*  26/12/2022 20.00

*Final situation:
Unit tests for taking notes feature and getting user id from username feature are implemented. With these unit tests get and post methods in app/views.py/noteApiView are tested. Additionally get method in app/views.py/getuseridAPIView is tested. Tests are running without an error.

*Reviewer* 
@egetaga 

*Reviewer Deadline* 26/12/2022 20.00

**Comment by egetaga** [comment]
I checked your unit tests and also approved the PR. I am closing the issue.
