### ISSUE TITLE
Backend - Bugfix in the profile page

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#851]
**Issue Description:**

While dockerizing and deploying the application today early in the morning, I realized that there is a bug in the patch method of the Profile view. It was an easy bug, so I fixed before the deployment. I will be fixing it in the repo ASAP. 

**Tasks to Do:**

- [ ] Fix the bug in the profile view

*Task Deadline:* 26.12.2022

*Final Situation:* Done

*Reviewer:*  @kkadirkkalkan

**Comment by egetaga** [comment]
The bug is there: 
![image](https://user-images.githubusercontent.com/42147612/209571026-adc548cf-1c71-4cd4-80e5-5e5c838cbf38.png)

**Comment by egetaga** [comment]
I committed my changes and also sent a PR request here https://github.com/bounswe/bounswe2022group1/pull/853. I am closing the issue as the bug is solved.

**Comment by kkadirkkalkan** [comment]
Since I tested the patch method and did not get an error, I did not check it again. Thank you for noticing the error and correcting it. I checked the pull request and it seems nice.

**Comment by kkadirkkalkan** [comment]
Since the bug is fixed I am closing this issue.
