### ISSUE TITLE
Research - chart drawing applications

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#88]
We should decide which chart drawing application we will use for diagrams.

Deadline: 05.04.2022

**Comment by ecesrkn** [comment]
**Lucidchart** seems to be a useful one among others since it allows us to work on the same project as a team, so we can constantly review each other's progress. Also, it provides nice templates for UML diagrams.

**Comment by kadirgokhann** [comment]
The most advantageous aspect is that we can work together at the same time. I totally agree with Ece.

**Comment by egetaga** [comment]
I agree with @ecesrkn and @kadirgokhann that we should use Lucidchart. Moreover, it provides free premium subscription if you are a university student and register with your edu e-mail.

**Comment by mstfatay** [comment]
I created a Lucidchart project. It has a template page for class diagrams. We can use this page to bootsrap our diagram.
Here is the [link](https://lucid.app/lucidchart/6896d855-3929-40fc-bec9-5e420a246899/edit?shared=true&page=zF0vqrVo4e-L#).
