### ISSUE TITLE
Class Diagram: Achievements

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#89]
In order to complete the achievements part of the class diagram, attributes, variables, objectives, and functions of the class should be specified in detail. How the functions return is also important for the class to make the class diagram clear.

Deadline:05.04.2022

**Comment by kadirgokhann** [comment]
[](https://i.ibb.co/mFCnJby/Ekran-Resmi-2022-04-05-01-03-45.png)

**Comment by mstfatay** [comment]
It looks great! However, types of the function arguments should be specified. Can you fix it? @kadirgokhann
