### ISSUE TITLE
Preparing Class Diagram for the Online Learning Project

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#90]
We need to prepare a detailed class diagram for the online learning project (OLP). The diagram shall include: 

- the relationship between classes, which should include but not limited to inheritance, aggregation and dependencies. 

- the classes required to provide the given functionality in the [requirements](https://github.com/bounswe/bounswe2022group1/wiki/Requirements).
-  these classes provide one of the most fundamental parts of our design process, so they should be consistent and clear.

All the choices taken related to the class diagram should be updated in this issue, so that everyone will be updated consistently.  
Moreover, as a team, we shall discuss and decide on:
- [x] all the required classes, their functionalities and fundamental fields.
- [x] everyone should be active in designing the main and fundamental parts of the diagram. 
- [x] assign the very specific, non-design based parts to individuals, like the name of the getters and setters, or very specific non-important functionalities of classes.
- [x] decide on which website or portal we will use for drawing the diagram. 
- [x] at the end, everyone should review the overall class diagram. 

When everyone reviews and modifies the diagram if necessary, this issue will be closed.

**Comment by omerozdemir1** [comment]
It seems all items are done. We can close the issue.
