### ISSUE TITLE
Class Diagram: Events

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#91]
After we already have decided on classes and class relations, I should add the corresponding 'box' with attributes and relation arcs to our shared Lucidchart workspace for the Class diagram.

**Comment by ecesrkn** [comment]
The task is completed. My work can be seen on the following [link](https://lucid.app/lucidchart/08733f3d-f1d2-4959-8c65-d71e0545c9f2/edit?invitationId=inv_fd1baad2-95e7-4994-968f-a8fb97c3a84a) concatanated to the whole diagram.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/43001709/161640538-707f09e5-fc3f-4d23-a706-93a0560d37e1.png">

**Comment by acyishere** [comment]
rewieved
