### ISSUE TITLE
Class Diagram: Note 

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#93]
In order to be able to make the "note" part in the "class diagram", necessary research should be done on this subject beforehand. functions, variables, and objectives should be determined and a class should be created according to them.

Deadline: 05.04.2022

**Comment by kadirgokhann** [comment]
<a href="https://ibb.co/tZgDkvR"><img src="https://i.ibb.co/7gPK8Zh/Ekran-Resmi-2022-04-05-01-14-37.png" alt="Ekran-Resmi-2022-04-05-01-14-37" border="0"></a>

Last version of the Note diagram.

**Comment by ecesrkn** [comment]
Nice work! It looks nearly perfect. Just a remark, maybe you could specify _params_ of _add_node_. Also, we should specify the data types of each parameter.

**Comment by harunerkurt** [comment]
I changed the add(params) method as add_note(content: string, user_id int, courser: course_id int):int

**Comment by harunerkurt** [comment]
I checked the diagram. There is no problem
