### ISSUE TITLE
Research on UML Class Diagram

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#95]
`Purpose:` Study the followings from [UML Class Diagram Tutorial](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/)

- What is a Class?
- UML Class Notation
- Perspectives of Class Diagram
- Relationships between classes 
- Class Diagram Example: Order System
- Class Diagram Example: GUI

`Estimated duration:` 2 hour

`Deadline:`  05/04/2022 22:00

**Comment by gecemavisioa** [comment]
I also checked the resource.

**Comment by acyishere** [comment]
Closing as i did the research as well
