### ISSUE TITLE
Research on UML Use Case Diagram

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#96]
`Purpose:`  Study the followings from [UML Use Case Diagram Tutorial](https://www.lucidchart.com/pages/uml-use-case-diagram)

- What is a use case diagram?
- When to apply use case diagrams
- Use case diagram components
- Use case diagram symbols and notation
- Use case diagram examples

`Estimated duration`: 2 hour

`Deadline:`  05/04/2022 22:00

**Comment by omerozdemir1** [comment]
I went over the resource, waiting for the others to complete it.

**Comment by gecemavisioa** [comment]
I also checked the resource.

**Comment by mstfatay** [comment]
Thanks for the resource! I read it, it was helpful.

**Comment by acyishere** [comment]
Researched
