### ISSUE TITLE
Class Diagram: Guest

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#97]
We decided the necessary qualifications of the guest class diagram on our meeting with team members:

- It shall extend the [User diagram](https://github.com/bounswe/bounswe2022group1/issues/94), which is an abstract class by means of inheritance.
- It should support sign_up, sign_in and forget_password operations. 
- All these functionalities are decided based on the requirements. 

According to these specifications, I shall draw a **Guest** diagram.

**Comment by egetaga** [comment]
According to the specified functionalities, which are decisions taken by all team members, I draw the following diagram. It may need further review and revision. So, review needed! 

- It has sign_in, sign_up and forget_password functionalities. 
- A guest user may search, so it has a search() method. 
- It extends the [User diagram. ](https://github.com/bounswe/bounswe2022group1/issues/94)
<img width="262" alt="Screen Shot 2022-04-05 at 11 37 05" src="https://user-images.githubusercontent.com/42147612/161713969-ece64cd6-43b6-45fa-9eb2-013b9dc451aa.png">

**Comment by ecesrkn** [comment]
I reviewed and I think it looks pretty good! Thank you @egetaga. I'm closing the issue.
