### ISSUE TITLE
Class Diagram: Statistics

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#98]
While designing and drawing the diagram for [Lecturer](https://github.com/bounswe/bounswe2022group1/issues/92#issuecomment-1088444658) we have realized that for course and teacher statistics, we need an aggregate data type. 

- So, a statistics class should be designed and drawed. 
- It should depend on **Lecturer** class and not be able to exist on its own.

**Comment by egetaga** [comment]
With discussion with team members, especially with @ecesrkn, @kadirgokhann  and @mstfatay , we designed the diagram as follows: 
<img width="427" alt="Screen Shot 2022-04-05 at 12 52 27" src="https://user-images.githubusercontent.com/42147612/161728445-a23b72f3-950f-4bbd-abfc-a4c476d96dc9.png">

**Comment by mstfatay** [comment]
Nice work! Diagram is very well created according to our discussion.

**Comment by egetaga** [comment]
As @mstfatay reviewed the diagram and applauded, I am closing the issue.
